In [1]:
# -*- coding: cp1252 -*-


from mechanize import Browser
import os
import pandas as pd
import html5lib
from bs4 import BeautifulSoup  


#os.chdir(r"E:\Dropbox\Dropbox\0_DB\A_Elaborazioni\Coeweb")

class coeweb(object):
    
    def __init__(self, link):
        self.pandas_db = pd.DataFrame()
        self.link = link
        br = Browser()
        br.open(self.link)
        br.select_form(nr=0)
        
        self.paesi = []
        self.paesi_descizione = []
        control = br.form.find_control("PAESE")
        if control.type == "select":  
            for item in control.items:
                self.paesi.append(item.name)
                self.paesi_descizione.append((item.name, str([label.text  for label in item.get_labels()])))
                
        self.territori = []
        self.territori_descrizione = []
        control = br.form.find_control("CODTERRITORIO")
        if control.type == "select":  
            for item in control.items:
                self.territori.append((item.name, str([label.text  for label in item.get_labels()])))
                self.territori_descrizione.append((item.name, str([label.text  for label in item.get_labels()])))
                
        self.anni = []
        control = br.form.find_control("ANNO")
        if control.type == "select":  
            for item in control.items:
                self.anni.append((item.name, str([label.text  for label in item.get_labels()])))
        self.mese = []
        control = br.form.find_control("MESE")
        if control.type == "select": 
            for item in control.items:
                self.mese.append((item.name, str([label.text  for label in item.get_labels()])))
        self.cumulato = []
        control = br.form.find_control("TIPOVALORE")
        for item in control.items:
            self.cumulato.append((item.name, str([label.text  for label in item.get_labels()])))
        
        self.bric = ['508', '720', '664', '75']
        #[('508', "['508 - Brasile']"), ('720', "['720 - Cina']"), ('664', "['664 - India']"), ('75', "['75 - Russia']")]
    
    def convert_string_euro(self,x):
        '''questa funzione rimuove la formattazione dei numeri di coeweb, trasformando il testo in numeri'''
        try: 
            return float(x.replace(".", ""))
        except:
            pass
    

    def scarica_uno(self, territorio = ["309048"], paese = ["1033"], cumulato = ['M'], anno = ["2013"], mese = ["4"]  ):# , paese, anno, trimestre, modalita)
        
        br = Browser()
        br.open(self.link)

        br.select_form(nr=0)

        control_territorio = br.form.find_control("CODTERRITORIO")
        br[control_territorio.name] = territorio #["309048"]

        control_paese = br.form.find_control("PAESE")
        br[control_paese.name] = paese #["309048"]

        control_anno = br.form.find_control("ANNO")
        br[control_anno.name] = anno #["309048"]

        control_mese = br.form.find_control("MESE")
        br[control_mese.name] = mese #["309048"]

        control_cumulato = br.form.find_control("TIPOVALORE")
        br[control_cumulato.name] = cumulato #["309048"]

        nome_stringa = territorio[0] + "_" + paese[0] + "_" + anno[0] + "_" + mese[0] + "_" + cumulato[0]


        response = br.submit()
        out_file = open(nome_stringa +".html", "w")
        out_file.write(response.read()) 
        out_file.close()
        #os.system("start " + nome_stringa +".html")
        self.dati = pd.read_html(nome_stringa +".html", header= 0, index_col=0, encoding = "cp1252")#'utf8'
        #os.remove(territorio[0] +".html")
        print "download_" + nome_stringa
        br.close()
        return self.dati
        
        # i dati dovrebbero essere raccolti in un pandas 
        
    def scarica_molti(self, territorio = ["309048"],   lista_paesi = None, lista_anni = None, lista_mesi = None, lista_cumulato = ["M"]):
        ''' questa funzione permette di scaricare per uno o più territori uno o più settori, per uno o più periodi di tempo'''
        #self.pandas_db = pd.DataFrame()
        
        def nome_paese(dati, codice):
            for item in dati:
                if item[0] == codice:
                    pulito1= item[1].split("'",)[1]
                    pulito2 = pulito1.split(" - ",)[1]
                    print pulito2
                    return pulito2
        
        def nome_territorio(dati, codice):
            for item in dati:
                if item[0] == codice:
                    try:
                        pulito1= item[1].split("'")[1]
                        pulito1 = pulito1.replace("-","")
                        pulito1 = pulito1.replace("'","")
                        return pulito1
                    except:
                        pass
        
        
        for item_territori in territorio:
            for item_paesi in lista_paesi:
                for item_anni in lista_anni:
                    for item_mesi in lista_mesi:

                        dataset =  self.scarica_uno([item_territori], paese = [str(item_paesi)],  anno = [str(item_anni)], mese = [str(item_mesi)], cumulato = lista_cumulato)
                        dataset = dataset[1]#.set_index(territorio, str(item_paesi), str(item_anni), str(item_mesi)])
                        
                        
                        dataset["territorio"] = nome_territorio(self.territori_descrizione,  item_territori)  
                        #dataset["territorio"] = item_territori
                        
                        #nome_paese(self.paesi_descizione, str(item_paesi))
                        dataset["paese"] = nome_paese(self.paesi_descizione, str(item_paesi))
                        dataset["anno"] = str(item_anni)
                        dataset["mese"] = str(item_mesi)
                        dataset["cumulato"] = lista_cumulato[0]
                        dataset.set_index(["territorio","paese","anno","mese","cumulato"], append = True, inplace = True)
                        dataset["DATI EXPORT"] = dataset["EXP" + str(item_anni)]
                          
                        
                        
                        dataset = dataset["DATI EXPORT"].apply(lambda x: self.convert_string_euro(x))
                        
                        
                        
                        # datasetcompleto
                        self.pandas_db = pd.concat([self.pandas_db, pd.DataFrame(dataset)])
                        # settori ateco disponibili
                        self.pandas_db.settori = set(self.pandas_db.reset_index()["Divisioni"])
                        
                            #print "errore_" + territorio[0] + "_" + str(item_paesi) + "_" + str(item_anni) + "_" + str(item_mesi) + "_" + lista_cumulato[0]



        print "eseguito"
    
    
    
    def analizza_settori(self, settori, interpolazione = "no"):
        ''' questa funzione restituisce un dataframe e un dizionario contenente le serie storiche per i settori inseriti come argomento [lista]. 
        Effettua anche l'interpolazione dei dati mancanti'''
        self.dict_settore = {}
        for item in settori:
            dati_settore = self.pandas_db.xs(item, level=0)
            if interpolazione == "yes":
                dati_settore["DATI EXPORT"] = dati_settore["DATI EXPORT"].apply(lambda x: convert_string_euro(x)).interpolate()
            else:
                dati_settore["DATI EXPORT"] = dati_settore["DATI EXPORT"].apply(lambda x: convert_string_euro(x))
            self.dict_settore[item] = dati_settore["DATI EXPORT"]
        self.dataframe_settori = pd.DataFrame(self.dict_settore)
        return self.dataframe_settori

In [2]:
def convert_string_euro(x):
    try: 
        return float(x.replace(".", ""))
    except:
        pass

In [3]:
os.getcwd()

'/home/scarselli/Scrivania/Coeweb Export/Coeweb Export'

In [4]:

lista_anni = [str(i) for i in range(2009,2016)]

In [5]:
Firenze = coeweb("http://www.coeweb.istat.it/predefinite/tutto_paese_merce.asp?livello=ATE07_AT2&riga=MERCE&territorio=S&AG=S")

In [6]:
Firenze.paesi_descizione

[('1', "['1 - Francia']"),
 ('2', "['2 - Belgio e Lussemburgo']"),
 ('3', "['3 - Paesi Bassi']"),
 ('4', "['4 - Germania']"),
 ('6', "['6 - Regno Unito']"),
 ('7', "['7 - Irlanda']"),
 ('8', "['8 - Danimarca']"),
 ('9', "['9 - Grecia']"),
 ('10', "['10 - Portogallo']"),
 ('11', "['11 - Spagna']"),
 ('17', "['17 - Belgio']"),
 ('18', "['18 - Lussemburgo']"),
 ('21', "['21 - Ceuta']"),
 ('22', "['22 - Ceuta e Melilla']"),
 ('23', "['23 - Melilla']"),
 ('24', "['24 - Islanda']"),
 ('25', "['25 - Isole F\\xe6r\\xf8er']"),
 ('27', "['27 - Svalbard (arcipelago delle)']"),
 ('28', "['28 - Norvegia']"),
 ('30', "['30 - Svezia']"),
 ('32', "['32 - Finlandia']"),
 ('37', "['37 - Liechtenstein']"),
 ('38', "['38 - Austria']"),
 ('39', "['39 - Svizzera']"),
 ('41', "['41 - Faer \\xd8er']"),
 ('43', "['43 - Andorra']"),
 ('44', "['44 - Gibilterra']"),
 ('45', "['45 - Santa Sede (Stato della Citt\\xe0 del Vaticano)']"),
 ('46', "['46 - Malta']"),
 ('47', "['47 - San Marino']"),
 ('48', "['48 - Iugoslavia']"),
 ('52', "['52 - Turchia']"),
 ('53', "['53 - Estonia']"),
 ('54', "['54 - Lettonia']"),
 ('55', "['55 - Lituania']"),
 ('56', "['56 - Unione Sovietica']"),
 ('60', "['60 - Polonia']"),
 ('61', "['61 - Repubblica ceca']"),
 ('62', "['62 - Cecoslovacchia']"),
 ('63', "['63 - Slovacchia']"),
 ('64', "['64 - Ungheria']"),
 ('66', "['66 - Romania']"),
 ('68', "['68 - Bulgaria']"),
 ('70', "['70 - Albania']"),
 ('72', "['72 - Ucraina']"),
 ('73', "['73 - Bielorussia']"),
 ('74', "['74 - Repubblica moldova']"),
 ('75', "['75 - Russia']"),
 ('76', "['76 - Georgia']"),
 ('77', "['77 - Armenia']"),
 ('78', "['78 - Azerbaigian']"),
 ('79', "['79 - Kazakhstan']"),
 ('80', "['80 - Turkmenistan']"),
 ('81', "['81 - Uzbekistan']"),
 ('82', "['82 - Tagikistan']"),
 ('83', "['83 - Kirghizistan']"),
 ('90', "['90 - Iugoslavia']"),
 ('91', "['91 - Slovenia']"),
 ('92', "['92 - Croazia']"),
 ('93', "['93 - Bosnia-Erzegovina']"),
 ('94', "['94 - Serbia e Montenegro']"),
 ('95', "['95 - Kosovo']"),
 ('96', "['96 - ex Repubblica iugoslava di Macedonia']"),
 ('97', "['97 - Montenegro']"),
 ('98', "['98 - Serbia']"),
 ('204', "['204 - Marocco']"),
 ('208', "['208 - Algeria']"),
 ('212', "['212 - Tunisia']"),
 ('216', "['216 - Libia']"),
 ('220', "['220 - Egitto']"),
 ('224', "['224 - Sudan']"),
 ('225', "['225 - Sud Sudan']"),
 ('228', "['228 - Mauritania']"),
 ('229', "['229 - Sahara occidentale']"),
 ('232', "['232 - Mali']"),
 ('236', "['236 - Burkina Faso']"),
 ('240', "['240 - Niger']"),
 ('244', "['244 - Ciad']"),
 ('247', "['247 - Capo Verde']"),
 ('248', "['248 - Senegal']"),
 ('252', "['252 - Gambia']"),
 ('257', "['257 - Guinea-Bissau']"),
 ('260', "['260 - Guinea']"),
 ('264', "['264 - Sierra Leone']"),
 ('268', "['268 - Liberia']"),
 ('272', '["272 - Costa d\'Avorio"]'),
 ('276', "['276 - Ghana']"),
 ('280', "['280 - Togo']"),
 ('284', "['284 - Benin']"),
 ('288', "['288 - Nigeria']"),
 ('302', "['302 - Camerun']"),
 ('306', "['306 - Repubblica centrafricana']"),
 ('310', "['310 - Guinea equatoriale']"),
 ('311', "['311 - S\\xe3o Tom\\xe9 e Principe']"),
 ('314', "['314 - Gabon']"),
 ('318', "['318 - Congo']"),
 ('322', "['322 - Repubblica democratica del Congo']"),
 ('324', "['324 - Ruanda']"),
 ('328', "['328 - Burundi']"),
 ('329', '["329 - Sant\'Elena, Ascensione e Tristan da Cunha"]'),
 ('330', "['330 - Angola']"),
 ('334', "['334 - Etiopia']"),
 ('336', "['336 - Eritrea']"),
 ('338', "['338 - Gibuti']"),
 ('342', "['342 - Somalia']"),
 ('346', "['346 - Kenya']"),
 ('350', "['350 - Uganda']"),
 ('352', "['352 - Repubblica unita di Tanzania']"),
 ('355', "['355 - Seychelles']"),
 ('357', '["357 - Territorio britannico dell\'Oceano Indiano"]'),
 ('366', "['366 - Mozambico']"),
 ('370', "['370 - Madagascar']"),
 ('372', "['372 - Riunione']"),
 ('373', "['373 - Maurizio']"),
 ('375', "['375 - Comore']"),
 ('377', "['377 - Mayotte']"),
 ('378', "['378 - Zambia']"),
 ('382', "['382 - Zimbabwe']"),
 ('386', "['386 - Malawi']"),
 ('388', "['388 - Sud Africa']"),
 ('389', "['389 - Namibia']"),
 ('391', "['391 - Botswana']"),
 ('393', "['393 - Swaziland']"),
 ('395', "['395 - Lesotho']"),
 ('400', "['400 - Stati Uniti']"),
 ('404', "['404 - Canada']"),
 ('406', "['406 - Groenlandia']"),
 ('408', "['408 - Saint Pierre e Miquelon']"),
 ('412', "['412 - Messico']"),
 ('413', "['413 - Bermuda']"),
 ('416', "['416 - Guatemala']"),
 ('421', "['421 - Belize']"),
 ('424', "['424 - Honduras']"),
 ('428', "['428 - El Salvador']"),
 ('432', "['432 - Nicaragua']"),
 ('436', "['436 - Costa Rica']"),
 ('442', "['442 - Panama']"),
 ('446', "['446 - Anguilla']"),
 ('448', "['448 - Cuba']"),
 ('449', "['449 - Saint Kitts e Nevis']"),
 ('452', "['452 - Haiti']"),
 ('453', "['453 - Bahamas']"),
 ('454', "['454 - Isole Turks e Caicos']"),
 ('456', "['456 - Repubblica dominicana']"),
 ('457', "['457 - Isole Vergini americane']"),
 ('458', "['458 - Guadalupa']"),
 ('459', "['459 - Antigua e Barbuda']"),
 ('460', "['460 - Dominica']"),
 ('461', "['461 - Isole Vergini britanniche']"),
 ('462', "['462 - Martinica']"),
 ('463', "['463 - Isole Cayman']"),
 ('464', "['464 - Giamaica']"),
 ('465', "['465 - Santa Lucia']"),
 ('466', "['466 - Saint-Barth\\xe9lemy']"),
 ('467', "['467 - Saint Vincent e Grenadine']"),
 ('468', "['468 - Isole Vergini britanniche']"),
 ('469', "['469 - Barbados']"),
 ('470', "['470 - Montserrat']"),
 ('472', "['472 - Trinidad e Tobago']"),
 ('473', "['473 - Grenada']"),
 ('474', "['474 - Aruba']"),
 ('475', "['475 - Cura\\xe7ao']"),
 ('477', "['477 - Bonaire, Sint Eustatius e Saba']"),
 ('478', "['478 - Antille Olandesi']"),
 ('479', "['479 - Sint Maarten']"),
 ('480', "['480 - Colombia']"),
 ('484', "['484 - Venezuela']"),
 ('488', "['488 - Guyana']"),
 ('492', "['492 - Suriname']"),
 ('496', "['496 - Guiana Francese']"),
 ('500', "['500 - Ecuador']"),
 ('504', "['504 - Per\\xf9']"),
 ('508', "['508 - Brasile']"),
 ('512', "['512 - Cile']"),
 ('516', "['516 - Bolivia']"),
 ('520', "['520 - Paraguay']"),
 ('524', "['524 - Uruguay']"),
 ('528', "['528 - Argentina']"),
 ('529', "['529 - Isole Falkland']"),
 ('600', "['600 - Cipro']"),
 ('604', "['604 - Libano']"),
 ('608', "['608 - Siria']"),
 ('612', "['612 - Iraq']"),
 ('616', '["616 - Repubblica islamica dell\'Iran"]'),
 ('624', "['624 - Israele']"),
 ('625', "['625 - Territorio palestinese occupato']"),
 ('626', "['626 - Timor-Leste']"),
 ('628', "['628 - Giordania']"),
 ('632', "['632 - Arabia Saudita']"),
 ('636', "['636 - Kuwait']"),
 ('640', "['640 - Bahrein']"),
 ('644', "['644 - Qatar']"),
 ('647', "['647 - Emirati Arabi Uniti']"),
 ('649', "['649 - Oman']"),
 ('653', "['653 - Yemen']"),
 ('660', "['660 - Afghanistan']"),
 ('662', "['662 - Pakistan']"),
 ('664', "['664 - India']"),
 ('666', "['666 - Bangladesh']"),
 ('667', "['667 - Maldive']"),
 ('669', "['669 - Sri Lanka']"),
 ('672', "['672 - Nepal']"),
 ('675', "['675 - Bhutan']"),
 ('676', "['676 - Birmania']"),
 ('680', "['680 - Thailandia']"),
 ('684', "['684 - Laos']"),
 ('690', "['690 - Vietnam']"),
 ('696', "['696 - Cambogia']"),
 ('700', "['700 - Indonesia']"),
 ('701', "['701 - Malaysia']"),
 ('703', "['703 - Brunei']"),
 ('706', "['706 - Singapore']"),
 ('708', "['708 - Filippine']"),
 ('716', "['716 - Mongolia']"),
 ('720', "['720 - Cina']"),
 ('724', "['724 - Corea del Nord']"),
 ('728', "['728 - Corea del Sud']"),
 ('732', "['732 - Giappone']"),
 ('736', "['736 - Taiwan']"),
 ('740', "['740 - Hong Kong']"),
 ('743', "['743 - Macao']"),
 ('800', "['800 - Australia']"),
 ('801', "['801 - Papua Nuova Guinea']"),
 ('802', "['802 - Oceania australiana']"),
 ('803', "['803 - Nauru']"),
 ('804', "['804 - Nuova Zelanda']"),
 ('806', "['806 - Isole Salomone']"),
 ('807', "['807 - Tuvalu']"),
 ('808', "['808 - Oceania americana']"),
 ('809', "['809 - Nuova Caledonia']"),
 ('810', "['810 - Oceania americana']"),
 ('811', "['811 - Wallis e Futuna']"),
 ('812', "['812 - Kiribati']"),
 ('813', "['813 - Isole Pitcairn']"),
 ('814', "['814 - Oceania neozelandese']"),
 ('815', "['815 - Figi']"),
 ('816', "['816 - Vanuatu']"),
 ('817', "['817 - Tonga']"),
 ('819', "['819 - Samoa']"),
 ('820', "['820 - Isole Marianne settentrionali']"),
 ('822', "['822 - Polinesia francese']"),
 ('823', "['823 - Stati Federati di Micronesia']"),
 ('824', "['824 - Isole Marshall']"),
 ('825', "['825 - Palau']"),
 ('830', "['830 - Samoa americane']"),
 ('831', "['831 - Guam']"),
 ('832', "['832 - Isole minori periferiche degli Stati Uniti']"),
 ('833', "['833 - Isole Cocos (Keeling)']"),
 ('834', "['834 - Isola Christmas']"),
 ('835', "['835 - Isole Heard e McDonald']"),
 ('836', "['836 - Isola Norfolk']"),
 ('837', "['837 - Isole Cook']"),
 ('838', "['838 - Niue']"),
 ('839', "['839 - Tokelau']"),
 ('890', "['890 - Regioni Polari']"),
 ('891', "['891 - Antartide']"),
 ('892', "['892 - Isola di Bouvet']"),
 ('893', "['893 - Georgia del Sud e Sandwich australi']"),
 ('894', "['894 - Terre australi e antartiche francesi']"),
 ('950', "['950 - Provviste e dotazioni di bordo']"),
 ('951',
  "['951 - Provviste e dotazioni di bordo nel quadro degli scambi intra UE']"),
 ('952',
  "['952 - Provviste e dotazioni di bordo nel quadro degli scambi con paesi terzi']"),
 ('955', "['955 - Alto mare']"),
 ('958', "['958 - Paesi e territori non specificati']"),
 ('959',
  "['959 - Paesi e territori non specificati nel quadro degli scambi intra UE']"),
 ('960',
  "['960 - Paesi e territori non specificati nel quadro degli scambi con i paesi terzi']"),
 ('962', "['962 - Punti e depositi franchi']"),
 ('977',
  "['977 - Paesi e territori non specificati per ragioni commerciali o militari']"),
 ('978',
  "['978 - Paesi e territori non specificati per ragioni commerciali o militari (intra UE)']"),
 ('979',
  "['979 - Paesi e territori non specificati per ragioni commerciali o militari (extra UE)']"),
 ('1001', "['1001 - [Area euro12]']"),
 ('1002', "['1002 - [Unione europea 15]']"),
 ('1004', "['1004 - [EFTA]']"),
 ('1005', "['1005 - [CEFTA]']"),
 ('1006', "['1006 - [COMESA]']"),
 ('1007', "['1007 - [SACU]']"),
 ('1008', "['1008 - [ASEAN]']"),
 ('1009', "['1009 - [NAFTA]']"),
 ('1010', '["1010 - [COMUNITA\' ANDINA]"]'),
 ('1011', "['1011 - [MERCOSUR]']"),
 ('1012', "['1012 - [OPEC]']"),
 ('1013', "['1013 - [EUROPA]']"),
 ('1015', "['1015 - [Paesi europei non Ue]']"),
 ('1016', "['1016 - [AFRICA]']"),
 ('1017', "['1017 - [Africa settentrionale]']"),
 ('1018', "['1018 - [Altri paesi africani]']"),
 ('1019', "['1019 - [AMERICA]']"),
 ('1020', "['1020 - [America settentrionale]']"),
 ('1021', "['1021 - [America centro-meridionale]']"),
 ('1022', "['1022 - [ASIA]']"),
 ('1023', "['1023 - [Medio Oriente]']"),
 ('1024', "['1024 - [Asia centrale]']"),
 ('1025', "['1025 - [Asia orientale]']"),
 ('1026', "['1026 - [Oceania]']"),
 ('1027', "['1027 - [Altri territori]']"),
 ('1028', "['1028 - [AREA DEL MEDITERRANEO]']"),
 ('1032', "['1032 - [Altre destinazioni]']"),
 ('1033', "['1033 - [MONDO]']"),
 ('1034', "['1034 - [OCEANIA E ALTRI TERRITORI]']"),
 ('1035', "['1035 - [NIEs]']"),
 ('1036', "['1036 - [Unione europea 25]']"),
 ('1038', "['1038 - [Unione europea 27]']"),
 ('1042', "['1042 - [EDA]']"),
 ('1044', "['1044 - [Area euro17]']"),
 ('1045', "['1045 - [Unione europea 28]']"),
 ('1046', "['1046 - [Extra Ue 28]']"),
 ('1047', "['1047 - [Area euro18]']"),
 ('1048', "['1048 - [BRICS]']"),
 ('1049', "['1049 - [APEC]']"),
 ('1050', "['1050 - [Area euro19]']")]

In [7]:
Firenze.territori_descrizione

toscana = [('309', "['---Toscana']"),
 ('309045', "['------Massa-Carrara']"),
 ('309046', "['------Lucca']"),
 ('309047', "['------Pistoia']"),
 ('309048', "['------Firenze']"),
 ('309049', "['------Livorno']"),
 ('309050', "['------Pisa']"),
 ('309051', "['------Arezzo']"),
 ('309052', "['------Siena']"),
 ('309053', "['------Grosseto']"),
 ('309100', "['------Prato']")]

In [8]:
metropolitana = [('309', "['---Toscana']"),
 ('309047', "['------Pistoia']"),
 ('309048', "['------Firenze']"),
 ('309100', "['------Prato']")]

In [9]:
CodiciToscana = []
for item in toscana:
    CodiciToscana.append(item[0])

In [10]:
CodiciMetropolitana = []
for item in metropolitana:
    CodiciMetropolitana.append(item[0])

In [11]:
Firenze.scarica_molti(territorio = CodiciMetropolitana, lista_paesi = ['6'], lista_anni = lista_anni, lista_mesi = ["9"], lista_cumulato = ['C'])

download_309_6_2009_9_C
Regno Unito
download_309_6_2010_9_C
Regno Unito
download_309_6_2011_9_C
Regno Unito
download_309_6_2012_9_C
Regno Unito
download_309_6_2013_9_C
Regno Unito
download_309_6_2014_9_C
Regno Unito
download_309_6_2015_9_C
Regno Unito
download_309047_6_2009_9_C
Regno Unito
download_309047_6_2010_9_C
Regno Unito
download_309047_6_2011_9_C
Regno Unito
download_309047_6_2012_9_C
Regno Unito
download_309047_6_2013_9_C
Regno Unito
download_309047_6_2014_9_C
Regno Unito
download_309047_6_2015_9_C
Regno Unito
download_309048_6_2009_9_C
Regno Unito
download_309048_6_2010_9_C
Regno Unito
download_309048_6_2011_9_C
Regno Unito
download_309048_6_2012_9_C
Regno Unito
download_309048_6_2013_9_C
Regno Unito
download_309048_6_2014_9_C
Regno Unito
download_309048_6_2015_9_C
Regno Unito
download_309100_6_2009_9_C
Regno Unito
download_309100_6_2010_9_C
Regno Unito
download_309100_6_2011_9_C
Regno Unito
download_309100_6_2012_9_C
Regno Unito
download_309100_6_2013_9_C
Regno Unito
download_309100_6_2014_9_C
Regno Unito
download_309100_6_2015_9_C
Regno Unito
eseguito

In [12]:
dati_toscana_completi = Firenze.pandas_db

In [13]:
dati_toscana_completi.to_excel("dati_metropolitana_completi.xlsx")

In [18]:
Firenze

In [19]:
dati_toscana_completi[dati_toscana_completi.index.get_level_values('Divisioni').isin(['Totale'])]

                                                     DATI EXPORT
Divisioni territorio paese       anno mese cumulato
Totale    Toscana    Regno Unito 2009 9    C          1528747209
                                 2010 9    C          1473169117
                                 2011 9    C          1519612834
                                 2012 9    C          1486383367
                                 2013 9    C          1615315910
                                 2014 9    C          1686906845
                                 2015 9    C          1802210027
          Pistoia    Regno Unito 2009 9    C            85316457
                                 2010 9    C            99959658
                                 2011 9    C           104536115
                                 2012 9    C            97534907
                                 2013 9    C           105228732
                                 2014 9    C           110815722
                                 2015 9    C           124232951
          Firenze    Regno Unito 2009 9    C           290155775
                                 2010 9    C           362372643
                                 2011 9    C           335666990
                                 2012 9    C           361374932
                                 2013 9    C           512352240
                                 2014 9    C           535248934
                                 2015 9    C           581639899
          Prato      Regno Unito 2009 9    C            82130808
                                 2010 9    C           114396829
                                 2011 9    C           108705991
                                 2012 9    C            90601437
                                 2013 9    C            93673380
                                 2014 9    C           111508702
                                 2015 9    C           142706401

In [20]:
Firenze_bric.to_excel("firenze_bric_db.xlsx")

NameError: name 'Firenze_bric' is not defined

In [125]:
#dir(Firenze)
def nome_territorio(dati, codice):
    for item in dati:
        if item[0] == codice:
            try:
                pulito1= item[1].split("'")[1]
                pulito1 = pulito1.replace("-","")
                pulito1 = pulito1.replace("'","")
                return pulito1
            except:
                pass

In [126]:
        
nome_territorio(Firenze.territori_descrizione, "309048")

'Firenze'

In [67]:
settori_da_analizzare = [
    "CA10-Prodotti alimentari",
    "CA11-Bevande",
    "CB13-Prodotti tessili",
    "CB14-Articoli di abbigliamento (anche in pelle e in pelliccia)", 
    "CB15-Articoli in pelle (escluso abbigliamento) e simili",
]

In [68]:
settori_da_analizzare = list(Firenze.pandas_db.settori)

In [69]:
settori_da_analizzare

[nan,
 u'MC74-Prodotti delle altre attivit\xe0 professionali, scientifiche e tecniche',
 u"AA03-Prodotti della pesca e dell'acquacoltura",
 u'CM32-Prodotti delle altre industrie manifatturiere',
 u'CD19-Coke e prodotti derivanti dalla raffinazione del petrolio',
 u'Totale',
 u'CK28-Macchinari e apparecchiature nca',
 u'BB08-Altri minerali da cave e miniere',
 u'CA11-Bevande',
 u'CL30-Altri mezzi di trasporto',
 u'CB13-Prodotti tessili',
 u'CA10-Prodotti alimentari',
 u'CA12-Tabacco',
 u'CF21-Prodotti farmaceutici di base e preparati farmaceutici',
 u'JA59-Prodotti delle attivit\xe0 di produzione cinematografica, video e programmi televisivi; registrazioni musicali e sonore',
 u'CG22-Articoli in gomma e materie plastiche',
 u'RR91-Prodotti delle attivit\xe0 di biblioteche, archivi, musei e di altre attivit\xe0 culturali',
 u'AA01-Prodotti agricoli, animali e della caccia',
 u'CG23-Altri prodotti della lavorazione di minerali non metalliferi',
 u'CH24-Prodotti della metallurgia',
 u"EE38-Prodotti delle attivit\xe0 di raccolta, trattamento e smaltimento dei rifiuti; prodotti dell'attivit\xe0 di recupero dei materiali",
 u'CB14-Articoli di abbigliamento (anche in pelle e in pelliccia)',
 u'BB07-Minerali metalliferi',
 u'CB15-Articoli in pelle (escluso abbigliamento) e simili',
 u'VV89-Merci dichiarate come provviste di bordo, merci nazionali di ritorno e respinte, merci varie',
 u'CI26-Computer e prodotti di elettronica e ottica; apparecchi elettromedicali, apparecchi di misurazione e orologi',
 u"RR90-Prodotti delle attivit\xe0 creative, artistiche e d'intrattenimento",
 u'CM31-Mobili',
 u'JA58-Prodotti delle attivit\xe0 editoriali',
 u'AA02-Prodotti della silvicoltura',
 u'CC17-Carta e prodotti di carta',
 u'CJ27-Apparecchiature elettriche e apparecchiature per uso domestico non elettriche',
 u'CE20-Prodotti chimici',
 u'CH25-Prodotti in metallo, esclusi macchinari e attrezzature',
 u'CC16-Legno e prodotti in legno e sughero (esclusi i mobili); articoli in paglia e materiali da intreccio',
 u'CL29-Autoveicoli, rimorchi e semirimorchi']

In [70]:
from numpy import nan

In [71]:
cleanedList

[nan,
 u'MC74-Prodotti delle altre attivit\xe0 professionali, scientifiche e tecniche',
 u"AA03-Prodotti della pesca e dell'acquacoltura",
 u'CM32-Prodotti delle altre industrie manifatturiere',
 u'CD19-Coke e prodotti derivanti dalla raffinazione del petrolio',
 u'Totale',
 u'CK28-Macchinari e apparecchiature nca',
 u'BB08-Altri minerali da cave e miniere',
 u'CA11-Bevande',
 u'CL30-Altri mezzi di trasporto',
 u'CB13-Prodotti tessili',
 u'CA10-Prodotti alimentari',
 u'CA12-Tabacco',
 u'CF21-Prodotti farmaceutici di base e preparati farmaceutici',
 u'JA59-Prodotti delle attivit\xe0 di produzione cinematografica, video e programmi televisivi; registrazioni musicali e sonore',
 u'CG22-Articoli in gomma e materie plastiche',
 u'RR91-Prodotti delle attivit\xe0 di biblioteche, archivi, musei e di altre attivit\xe0 culturali',
 u'AA01-Prodotti agricoli, animali e della caccia',
 u'CG23-Altri prodotti della lavorazione di minerali non metalliferi',
 u'CH24-Prodotti della metallurgia',
 u"EE38-Prodotti delle attivit\xe0 di raccolta, trattamento e smaltimento dei rifiuti; prodotti dell'attivit\xe0 di recupero dei materiali",
 u'CB14-Articoli di abbigliamento (anche in pelle e in pelliccia)',
 u'BB07-Minerali metalliferi',
 u'CB15-Articoli in pelle (escluso abbigliamento) e simili',
 u'VV89-Merci dichiarate come provviste di bordo, merci nazionali di ritorno e respinte, merci varie',
 u'CI26-Computer e prodotti di elettronica e ottica; apparecchi elettromedicali, apparecchi di misurazione e orologi',
 u"RR90-Prodotti delle attivit\xe0 creative, artistiche e d'intrattenimento",
 u'CM31-Mobili',
 u'JA58-Prodotti delle attivit\xe0 editoriali',
 u'AA02-Prodotti della silvicoltura',
 u'CC17-Carta e prodotti di carta',
 u'CJ27-Apparecchiature elettriche e apparecchiature per uso domestico non elettriche',
 u'CE20-Prodotti chimici',
 u'CH25-Prodotti in metallo, esclusi macchinari e attrezzature',
 u'CC16-Legno e prodotti in legno e sughero (esclusi i mobili); articoli in paglia e materiali da intreccio',
 u'CL29-Autoveicoli, rimorchi e semirimorchi']

In [72]:
cleanedList[1:]

[u'MC74-Prodotti delle altre attivit\xe0 professionali, scientifiche e tecniche',
 u"AA03-Prodotti della pesca e dell'acquacoltura",
 u'CM32-Prodotti delle altre industrie manifatturiere',
 u'CD19-Coke e prodotti derivanti dalla raffinazione del petrolio',
 u'Totale',
 u'CK28-Macchinari e apparecchiature nca',
 u'BB08-Altri minerali da cave e miniere',
 u'CA11-Bevande',
 u'CL30-Altri mezzi di trasporto',
 u'CB13-Prodotti tessili',
 u'CA10-Prodotti alimentari',
 u'CA12-Tabacco',
 u'CF21-Prodotti farmaceutici di base e preparati farmaceutici',
 u'JA59-Prodotti delle attivit\xe0 di produzione cinematografica, video e programmi televisivi; registrazioni musicali e sonore',
 u'CG22-Articoli in gomma e materie plastiche',
 u'RR91-Prodotti delle attivit\xe0 di biblioteche, archivi, musei e di altre attivit\xe0 culturali',
 u'AA01-Prodotti agricoli, animali e della caccia',
 u'CG23-Altri prodotti della lavorazione di minerali non metalliferi',
 u'CH24-Prodotti della metallurgia',
 u"EE38-Prodotti delle attivit\xe0 di raccolta, trattamento e smaltimento dei rifiuti; prodotti dell'attivit\xe0 di recupero dei materiali",
 u'CB14-Articoli di abbigliamento (anche in pelle e in pelliccia)',
 u'BB07-Minerali metalliferi',
 u'CB15-Articoli in pelle (escluso abbigliamento) e simili',
 u'VV89-Merci dichiarate come provviste di bordo, merci nazionali di ritorno e respinte, merci varie',
 u'CI26-Computer e prodotti di elettronica e ottica; apparecchi elettromedicali, apparecchi di misurazione e orologi',
 u"RR90-Prodotti delle attivit\xe0 creative, artistiche e d'intrattenimento",
 u'CM31-Mobili',
 u'JA58-Prodotti delle attivit\xe0 editoriali',
 u'AA02-Prodotti della silvicoltura',
 u'CC17-Carta e prodotti di carta',
 u'CJ27-Apparecchiature elettriche e apparecchiature per uso domestico non elettriche',
 u'CE20-Prodotti chimici',
 u'CH25-Prodotti in metallo, esclusi macchinari e attrezzature',
 u'CC16-Legno e prodotti in legno e sughero (esclusi i mobili); articoli in paglia e materiali da intreccio',
 u'CL29-Autoveicoli, rimorchi e semirimorchi']

In [73]:
Firenze.analizza_settori(cleanedList[1:])

-c:135: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_index,col_indexer] = value instead

                                     AA01-Prodotti agricoli, animali e della caccia  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                      0
                 2001 9    C                                                  13025
                 2002 9    C                                                  15566
                 2003 9    C                                                      0
                 2004 9    C                                                 770260
                 2005 9    C                                                2061656
                 2006 9    C                                                    NaN
                 2007 9    C                                                 311569
                 2008 9    C                                                  66951
                 2009 9    C                                                   9694
                 2010 9    C                                                  29423
                 2011 9    C                                                 127306
                 2012 9    C                                                 646598
                 2013 9    C                                                 896766

                                     AA02-Prodotti della silvicoltura  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                        0
                 2001 9    C                                        0
                 2002 9    C                                        0
                 2003 9    C                                        0
                 2004 9    C                                        0
                 2005 9    C                                      NaN
                 2006 9    C                                      NaN
                 2007 9    C                                      NaN
                 2008 9    C                                      NaN
                 2009 9    C                                      NaN
                 2010 9    C                                      NaN
                 2011 9    C                                      NaN
                 2012 9    C                                      NaN
                 2013 9    C                                      NaN

                                     AA03-Prodotti della pesca e dell'acquacoltura  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                   NaN
                 2001 9    C                                                   NaN
                 2002 9    C                                                   NaN
                 2003 9    C                                                   NaN
                 2004 9    C                                                   NaN
                 2005 9    C                                                   NaN
                 2006 9    C                                                   NaN
                 2007 9    C                                                   NaN
                 2008 9    C                                                   NaN
                 2009 9    C                                                   NaN
                 2010 9    C                                                   NaN
                 2011 9    C                                                   NaN
                 2012 9    C                                                   NaN
                 2013 9    C                                                  2383

                                     BB07-Minerali metalliferi  \
territorio paese anno mese cumulato
309048     75    2000 9    C                               NaN
                 2001 9    C                             67904
                 2002 9    C                             95338
                 2003 9    C                            134739
                 2004 9    C                            116397
                 2005 9    C                            165738
                 2006 9    C                               NaN
                 2007 9    C                             44500
                 2008 9    C                            216000
                 2009 9    C                            175288
                 2010 9    C                            142186
                 2011 9    C                            308630
                 2012 9    C                            116221
                 2013 9    C                             29220

                                     BB08-Altri minerali da cave e miniere  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                         57172
                 2001 9    C                                         16543
                 2002 9    C                                          8609
                 2003 9    C                                             0
                 2004 9    C                                         23293
                 2005 9    C                                             0
                 2006 9    C                                           NaN
                 2007 9    C                                         25297
                 2008 9    C                                         56324
                 2009 9    C                                         29404
                 2010 9    C                                        120438
                 2011 9    C                                         29182
                 2012 9    C                                        380349
                 2013 9    C                                        346218

                                     CA10-Prodotti alimentari  CA11-Bevande  \
territorio paese anno mese cumulato
309048     75    2000 9    C                           137322        372825
                 2001 9    C                           100698        436301
                 2002 9    C                           300282        863777
                 2003 9    C                           252840       1655941
                 2004 9    C                          1312581       2498208
                 2005 9    C                          1607233       4360622
                 2006 9    C                              NaN           NaN
                 2007 9    C                          2655542       3096940
                 2008 9    C                          1987585       5022565
                 2009 9    C                          1214299       4229238
                 2010 9    C                          1535530       6636740
                 2011 9    C                          1667930       4198169
                 2012 9    C                          2603208       2339577
                 2013 9    C                          2575783       2643145

                                     CA12-Tabacco  CB13-Prodotti tessili  \
territorio paese anno mese cumulato
309048     75    2000 9    C                  NaN                2770822
                 2001 9    C                  NaN                4889621
                 2002 9    C                  NaN                7549762
                 2003 9    C                  NaN                6234286
                 2004 9    C               165050                5683685
                 2005 9    C                    0                3843475
                 2006 9    C                  NaN                    NaN
                 2007 9    C                53752                3394069
                 2008 9    C                    0                4469893
                 2009 9    C                    0                1961118
                 2010 9    C                  NaN                2637437
                 2011 9    C                  NaN                3980858
                 2012 9    C                  NaN                3978612
                 2013 9    C                  NaN                4150549

                                     CB14-Articoli di abbigliamento (anche in pelle e in pelliccia)  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                  12579922
                 2001 9    C                                                  19739363
                 2002 9    C                                                  24227762
                 2003 9    C                                                  24978527
                 2004 9    C                                                  27302141
                 2005 9    C                                                  40369183
                 2006 9    C                                                       NaN
                 2007 9    C                                                  70449187
                 2008 9    C                                                  83028888
                 2009 9    C                                                  41561791
                 2010 9    C                                                  27123716
                 2011 9    C                                                  45113391
                 2012 9    C                                                  47639290
                 2013 9    C                                                  57797345

                                                                  ...                                \
territorio paese anno mese cumulato                               ...
309048     75    2000 9    C                                      ...
                 2001 9    C                                      ...
                 2002 9    C                                      ...
                 2003 9    C                                      ...
                 2004 9    C                                      ...
                 2005 9    C                                      ...
                 2006 9    C                                      ...
                 2007 9    C                                      ...
                 2008 9    C                                      ...
                 2009 9    C                                      ...
                 2010 9    C                                      ...
                 2011 9    C                                      ...
                 2012 9    C                                      ...
                 2013 9    C                                      ...

                                     CM31-Mobili  \
territorio paese anno mese cumulato
309048     75    2000 9    C             4851742
                 2001 9    C             6154803
                 2002 9    C             5753490
                 2003 9    C             6607215
                 2004 9    C             8886708
                 2005 9    C            10751605
                 2006 9    C                 NaN
                 2007 9    C            14592628
                 2008 9    C            17955026
                 2009 9    C            12680183
                 2010 9    C             8763392
                 2011 9    C            11973562
                 2012 9    C            15792592
                 2013 9    C            21164610

                                     CM32-Prodotti delle altre industrie manifatturiere  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                   1739860
                 2001 9    C                                                   1835203
                 2002 9    C                                                   2458319
                 2003 9    C                                                   2814573
                 2004 9    C                                                   4017794
                 2005 9    C                                                   3083863
                 2006 9    C                                                       NaN
                 2007 9    C                                                   7060050
                 2008 9    C                                                   6958189
                 2009 9    C                                                   3299771
                 2010 9    C                                                   6318120
                 2011 9    C                                                   4694671
                 2012 9    C                                                   5953297
                 2013 9    C                                                   8239303

                                     EE38-Prodotti delle attività di raccolta, trattamento e smaltimento dei rifiuti; prodotti dell'attività di recupero dei materiali  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                         0
                 2001 9    C                                                         0
                 2002 9    C                                                         0
                 2003 9    C                                                       NaN
                 2004 9    C                                                       NaN
                 2005 9    C                                                      2117
                 2006 9    C                                                       NaN
                 2007 9    C                                                      7125
                 2008 9    C                                                         0
                 2009 9    C                                                         0
                 2010 9    C                                                     17200
                 2011 9    C                                                         0
                 2012 9    C                                                         0
                 2013 9    C                                                      6400

                                     JA58-Prodotti delle attività editoriali  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                          580411
                 2001 9    C                                          586437
                 2002 9    C                                          168443
                 2003 9    C                                          124476
                 2004 9    C                                          383602
                 2005 9    C                                          460616
                 2006 9    C                                             NaN
                 2007 9    C                                          385116
                 2008 9    C                                          314840
                 2009 9    C                                          247779
                 2010 9    C                                          253892
                 2011 9    C                                          143333
                 2012 9    C                                          142867
                 2013 9    C                                           55589

                                     JA59-Prodotti delle attività di produzione cinematografica, video e programmi televisivi; registrazioni musicali e sonore  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                      3615
                 2001 9    C                                                      4426
                 2002 9    C                                                     11000
                 2003 9    C                                                       800
                 2004 9    C                                                       635
                 2005 9    C                                                       630
                 2006 9    C                                                       NaN
                 2007 9    C                                                         0
                 2008 9    C                                                         0
                 2009 9    C                                                      5263
                 2010 9    C                                                     21690
                 2011 9    C                                                         0
                 2012 9    C                                                     20411
                 2013 9    C                                                      5823

                                     MC74-Prodotti delle altre attività professionali, scientifiche e tecniche  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                       NaN
                 2001 9    C                                                       NaN
                 2002 9    C                                                       NaN
                 2003 9    C                                                       NaN
                 2004 9    C                                                      1479
                 2005 9    C                                                         0
                 2006 9    C                                                       NaN
                 2007 9    C                                                       NaN
                 2008 9    C                                                       NaN
                 2009 9    C                                                       NaN
                 2010 9    C                                                      4760
                 2011 9    C                                                     30201
                 2012 9    C                                                     29996
                 2013 9    C                                                     26230

                                     RR90-Prodotti delle attività creative, artistiche e d'intrattenimento  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                     28152
                 2001 9    C                                                         0
                 2002 9    C                                                      7016
                 2003 9    C                                                         0
                 2004 9    C                                                     43693
                 2005 9    C                                                    236803
                 2006 9    C                                                       NaN
                 2007 9    C                                                     13101
                 2008 9    C                                                     56186
                 2009 9    C                                                     20802
                 2010 9    C                                                     92778
                 2011 9    C                                                    101714
                 2012 9    C                                                     33410
                 2013 9    C                                                     43759

                                     RR91-Prodotti delle attività di biblioteche, archivi, musei e di altre attività culturali  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                      9141
                 2001 9    C                                                         0
                 2002 9    C                                                      7540

In [58]:
Firenze.analizza_settori(cleanedList[1:])

-c:132: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_index,col_indexer] = value instead

                                     AA01-Prodotti agricoli, animali e della caccia  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                    0.0
                 2001 9    C                                                13025.0
                 2002 9    C                                                15566.0
                 2003 9    C                                                    0.0
                 2004 9    C                                               770260.0
                 2005 9    C                                              2061656.0
                 2006 9    C                                              1186612.5
                 2007 9    C                                               311569.0
                 2008 9    C                                                66951.0
                 2009 9    C                                                 9694.0
                 2010 9    C                                                29423.0
                 2011 9    C                                               127306.0
                 2012 9    C                                               646598.0
                 2013 9    C                                               896766.0

                                     AA02-Prodotti della silvicoltura  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                        0
                 2001 9    C                                        0
                 2002 9    C                                        0
                 2003 9    C                                        0
                 2004 9    C                                        0
                 2005 9    C                                      NaN
                 2006 9    C                                      NaN
                 2007 9    C                                      NaN
                 2008 9    C                                      NaN
                 2009 9    C                                      NaN
                 2010 9    C                                      NaN
                 2011 9    C                                      NaN
                 2012 9    C                                      NaN
                 2013 9    C                                      NaN

                                     AA03-Prodotti della pesca e dell'acquacoltura  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                   NaN
                 2001 9    C                                                   NaN
                 2002 9    C                                                   NaN
                 2003 9    C                                                   NaN
                 2004 9    C                                                   NaN
                 2005 9    C                                                   NaN
                 2006 9    C                                                   NaN
                 2007 9    C                                                   NaN
                 2008 9    C                                                   NaN
                 2009 9    C                                                   NaN
                 2010 9    C                                                   NaN
                 2011 9    C                                                   NaN
                 2012 9    C                                                   NaN
                 2013 9    C                                                  2383

                                     BB07-Minerali metalliferi  \
territorio paese anno mese cumulato
309048     75    2000 9    C                               NaN
                 2001 9    C                             67904
                 2002 9    C                             95338
                 2003 9    C                            134739
                 2004 9    C                            116397
                 2005 9    C                            165738
                 2006 9    C                            105119
                 2007 9    C                             44500
                 2008 9    C                            216000
                 2009 9    C                            175288
                 2010 9    C                            142186
                 2011 9    C                            308630
                 2012 9    C                            116221
                 2013 9    C                             29220

                                     BB08-Altri minerali da cave e miniere  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                       57172.0
                 2001 9    C                                       16543.0
                 2002 9    C                                        8609.0
                 2003 9    C                                           0.0
                 2004 9    C                                       23293.0
                 2005 9    C                                           0.0
                 2006 9    C                                       12648.5
                 2007 9    C                                       25297.0
                 2008 9    C                                       56324.0
                 2009 9    C                                       29404.0
                 2010 9    C                                      120438.0
                 2011 9    C                                       29182.0
                 2012 9    C                                      380349.0
                 2013 9    C                                      346218.0

                                     CA10-Prodotti alimentari  CA11-Bevande  \
territorio paese anno mese cumulato
309048     75    2000 9    C                         137322.0        372825
                 2001 9    C                         100698.0        436301
                 2002 9    C                         300282.0        863777
                 2003 9    C                         252840.0       1655941
                 2004 9    C                        1312581.0       2498208
                 2005 9    C                        1607233.0       4360622
                 2006 9    C                        2131387.5       3728781
                 2007 9    C                        2655542.0       3096940
                 2008 9    C                        1987585.0       5022565
                 2009 9    C                        1214299.0       4229238
                 2010 9    C                        1535530.0       6636740
                 2011 9    C                        1667930.0       4198169
                 2012 9    C                        2603208.0       2339577
                 2013 9    C                        2575783.0       2643145

                                     CA12-Tabacco  CB13-Prodotti tessili  \
territorio paese anno mese cumulato
309048     75    2000 9    C                  NaN                2770822
                 2001 9    C                  NaN                4889621
                 2002 9    C                  NaN                7549762
                 2003 9    C                  NaN                6234286
                 2004 9    C               165050                5683685
                 2005 9    C                    0                3843475
                 2006 9    C                26876                3618772
                 2007 9    C                53752                3394069
                 2008 9    C                    0                4469893
                 2009 9    C                    0                1961118
                 2010 9    C                  NaN                2637437
                 2011 9    C                  NaN                3980858
                 2012 9    C                  NaN                3978612
                 2013 9    C                  NaN                4150549

                                     CB14-Articoli di abbigliamento (anche in pelle e in pelliccia)  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                  12579922
                 2001 9    C                                                  19739363
                 2002 9    C                                                  24227762
                 2003 9    C                                                  24978527
                 2004 9    C                                                  27302141
                 2005 9    C                                                  40369183
                 2006 9    C                                                  55409185
                 2007 9    C                                                  70449187
                 2008 9    C                                                  83028888
                 2009 9    C                                                  41561791
                 2010 9    C                                                  27123716
                 2011 9    C                                                  45113391
                 2012 9    C                                                  47639290
                 2013 9    C                                                  57797345

                                                                  ...                                \
territorio paese anno mese cumulato                               ...
309048     75    2000 9    C                                      ...
                 2001 9    C                                      ...
                 2002 9    C                                      ...
                 2003 9    C                                      ...
                 2004 9    C                                      ...
                 2005 9    C                                      ...
                 2006 9    C                                      ...
                 2007 9    C                                      ...
                 2008 9    C                                      ...
                 2009 9    C                                      ...
                 2010 9    C                                      ...
                 2011 9    C                                      ...
                 2012 9    C                                      ...
                 2013 9    C                                      ...

                                     CM31-Mobili  \
territorio paese anno mese cumulato
309048     75    2000 9    C           4851742.0
                 2001 9    C           6154803.0
                 2002 9    C           5753490.0
                 2003 9    C           6607215.0
                 2004 9    C           8886708.0
                 2005 9    C          10751605.0
                 2006 9    C          12672116.5
                 2007 9    C          14592628.0
                 2008 9    C          17955026.0
                 2009 9    C          12680183.0
                 2010 9    C           8763392.0
                 2011 9    C          11973562.0
                 2012 9    C          15792592.0
                 2013 9    C          21164610.0

                                     CM32-Prodotti delle altre industrie manifatturiere  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                 1739860.0
                 2001 9    C                                                 1835203.0
                 2002 9    C                                                 2458319.0
                 2003 9    C                                                 2814573.0
                 2004 9    C                                                 4017794.0
                 2005 9    C                                                 3083863.0
                 2006 9    C                                                 5071956.5
                 2007 9    C                                                 7060050.0
                 2008 9    C                                                 6958189.0
                 2009 9    C                                                 3299771.0
                 2010 9    C                                                 6318120.0
                 2011 9    C                                                 4694671.0
                 2012 9    C                                                 5953297.0
                 2013 9    C                                                 8239303.0

                                     EE38-Prodotti delle attività di raccolta, trattamento e smaltimento dei rifiuti; prodotti dell'attività di recupero dei materiali  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                         0
                 2001 9    C                                                         0
                 2002 9    C                                                         0
                 2003 9    C                                                       NaN
                 2004 9    C                                                       NaN
                 2005 9    C                                                      2117
                 2006 9    C                                                      4621
                 2007 9    C                                                      7125
                 2008 9    C                                                         0
                 2009 9    C                                                         0
                 2010 9    C                                                     17200
                 2011 9    C                                                         0
                 2012 9    C                                                         0
                 2013 9    C                                                      6400

                                     JA58-Prodotti delle attività editoriali  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                          580411
                 2001 9    C                                          586437
                 2002 9    C                                          168443
                 2003 9    C                                          124476
                 2004 9    C                                          383602
                 2005 9    C                                          460616
                 2006 9    C                                          422866
                 2007 9    C                                          385116
                 2008 9    C                                          314840
                 2009 9    C                                          247779
                 2010 9    C                                          253892
                 2011 9    C                                          143333
                 2012 9    C                                          142867
                 2013 9    C                                           55589

                                     JA59-Prodotti delle attività di produzione cinematografica, video e programmi televisivi; registrazioni musicali e sonore  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                      3615
                 2001 9    C                                                      4426
                 2002 9    C                                                     11000
                 2003 9    C                                                       800
                 2004 9    C                                                       635
                 2005 9    C                                                       630
                 2006 9    C                                                       315
                 2007 9    C                                                         0
                 2008 9    C                                                         0
                 2009 9    C                                                      5263
                 2010 9    C                                                     21690
                 2011 9    C                                                         0
                 2012 9    C                                                     20411
                 2013 9    C                                                      5823

                                     MC74-Prodotti delle altre attività professionali, scientifiche e tecniche  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                       NaN
                 2001 9    C                                                       NaN
                 2002 9    C                                                       NaN
                 2003 9    C                                                       NaN
                 2004 9    C                                                      1479
                 2005 9    C                                                         0
                 2006 9    C                                                      2380
                 2007 9    C                                                       NaN
                 2008 9    C                                                       NaN
                 2009 9    C                                                       NaN
                 2010 9    C                                                      4760
                 2011 9    C                                                     30201
                 2012 9    C                                                     29996
                 2013 9    C                                                     26230

                                     RR90-Prodotti delle attività creative, artistiche e d'intrattenimento  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                     28152
                 2001 9    C                                                         0
                 2002 9    C                                                      7016
                 2003 9    C                                                         0
                 2004 9    C                                                     43693
                 2005 9    C                                                    236803
                 2006 9    C                                                    124952
                 2007 9    C                                                     13101
                 2008 9    C                                                     56186
                 2009 9    C                                                     20802
                 2010 9    C                                                     92778
                 2011 9    C                                                    101714
                 2012 9    C                                                     33410
                 2013 9    C                                                     43759

                                     RR91-Prodotti delle attività di biblioteche, archivi, musei e di altre attività culturali  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                      9141
                 2001 9    C                                                         0
                 2002 9    C                                                      7540

In [38]:
Firenze.dataframe_settori[0]

                                     CB14-Articoli di abbigliamento (anche in pelle e in pelliccia)  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                  12579922
                 2001 9    C                                                  19739363
                 2002 9    C                                                  24227762
                 2003 9    C                                                  24978527
                 2004 9    C                                                  27302141
                 2005 9    C                                                  40369183
                 2006 9    C                                                  55409185
                 2007 9    C                                                  70449187
                 2008 9    C                                                  83028888
                 2009 9    C                                                  41561791
                 2010 9    C                                                  27123716
                 2011 9    C                                                  45113391
                 2012 9    C                                                  47639290
                 2013 9    C                                                  57797345

                                     CB15-Articoli in pelle (escluso abbigliamento) e simili
territorio paese anno mese cumulato
309048     75    2000 9    C                                                 3074113.0
                 2001 9    C                                                 5937865.0
                 2002 9    C                                                 4469771.0
                 2003 9    C                                                 5557355.0
                 2004 9    C                                                 7071724.0
                 2005 9    C                                                10479503.0
                 2006 9    C                                                17372926.5
                 2007 9    C                                                24266350.0
                 2008 9    C                                                34813104.0
                 2009 9    C                                                21669093.0
                 2010 9    C                                                20307464.0
                 2011 9    C                                                24938104.0
                 2012 9    C                                                31612137.0
                 2013 9    C                                                51948468.0

                                     CB14-Articoli di abbigliamento (anche in pelle e in pelliccia)  \
territorio paese anno mese cumulato
309048     75    2000 9    C                                                  12579922
                 2001 9    C                                                  19739363
                 2002 9    C                                                  24227762
                 2003 9    C                                                  24978527
                 2004 9    C                                                  27302141
                 2005 9    C                                                  40369183
                 2006 9    C                                                  55409185
                 2007 9    C                                                  70449187
                 2008 9    C                                                  83028888
                 2009 9    C                                                  41561791
                 2010 9    C                                                  27123716
                 2011 9    C                                                  45113391
                 2012 9    C                                                  47639290
                 2013 9    C                                                  57797345

                                     CB15-Articoli in pelle (escluso abbigliamento) e simili
territorio paese anno mese cumulato
309048     75    2000 9    C                                                 3074113.0
                 2001 9    C                                                 5937865.0
                 2002 9    C                                                 4469771.0
                 2003 9    C                                                 5557355.0
                 2004 9    C                                                 7071724.0
                 2005 9    C                                                10479503.0
                 2006 9    C                                                17372926.5
                 2007 9    C                                                24266350.0
                 2008 9    C                                                34813104.0
                 2009 9    C                                                21669093.0
                 2010 9    C                                                20307464.0
                 2011 9    C                                                24938104.0
                 2012 9    C                                                31612137.0
                 2013 9    C                                                51948468.0

In [16]:
russia_pelle = Firenze.pandas_db.xs(settori_da_analizzare, level=0)

KeyError: 'Key length (2) was greater than MultiIndex lexsort depth (0)'

In [73]:
russia_pelle["DATI EXPORT"] = russia_pelle["DATI EXPORT"].apply(lambda x: convert_string_euro(x)).interpolate()

-c:1: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_index,col_indexer] = value instead

In [74]:
russia_abbigliamento = Firenze.pandas_db.xs("CB14-Articoli di abbigliamento (anche in pelle e in pelliccia)", level=0)

In [75]:
russia_abbigliamento["DATI EXPORT"] = russia_abbigliamento["DATI EXPORT"].apply(lambda x: convert_string_euro(x)).interpolate()

In [76]:
russia_tessile = Firenze.pandas_db.xs("CB13-Prodotti tessili", level=0)

In [77]:
russia_tessile["DATI EXPORT"] = russia_tessile["DATI EXPORT"].apply(lambda x: convert_string_euro(x)).interpolate()

In [78]:
russia_tessile

                                     DATI EXPORT
territorio paese anno mese cumulato
309048     75    2000 9    C             2770822
                 2001 9    C             4889621
                 2002 9    C             7549762
                 2003 9    C             6234286
                 2004 9    C             5683685
                 2005 9    C             3843475
                 2006 9    C             3618772
                 2007 9    C             3394069
                 2008 9    C             4469893
                 2009 9    C             1961118
                 2010 9    C             2637437
                 2011 9    C             3980858
                 2012 9    C             3978612
                 2013 9    C             4150549

In [79]:
russia_moda = russia_tessile + russia_abbigliamento + russia_pelle

In [80]:
russia_moda

                                     DATI EXPORT
territorio paese anno mese cumulato
309048     75    2000 9    C          18424857.0
                 2001 9    C          30566849.0
                 2002 9    C          36247295.0
                 2003 9    C          36770168.0
                 2004 9    C          40057550.0
                 2005 9    C          54692161.0
                 2006 9    C          76400883.5
                 2007 9    C          98109606.0
                 2008 9    C         122311885.0
                 2009 9    C          65192002.0
                 2010 9    C          50068617.0
                 2011 9    C          74032353.0
                 2012 9    C          83230039.0
                 2013 9    C         113896362.0

In [82]:
writer = pd.ExcelWriter('output.xlsx')
russia_pelle.to_excel(writer,'pelle')
russia_abbigliamento.to_excel(writer,'abbigliamento')
russia_tessile.to_excel(writer,'tessile')
russia_moda.to_excel(writer,'moda')
writer.save()

In [52]:
russia["DATI EXPORT"].apply(lambda x: convert_string_euro(x)).interpolate()

territorio  paese  anno  mese  cumulato
309048      75     2000  9     C            53714988.0
                   2001  9     C           100558311.0
                   2002  9     C           108431524.0
                   2003  9     C            82237656.0
                   2004  9     C           103713482.0
                   2005  9     C           305372412.0
                   2006  9     C           282533038.5
                   2007  9     C           259693665.0
                   2008  9     C           235949204.0
                   2009  9     C           178188726.0
                   2010  9     C           159871451.0
                   2011  9     C           234999174.0
                   2012  9     C           241138686.0
                   2013  9     C           299414649.0
Name: DATI EXPORT, dtype: float64

In [54]:
russia["DATI EXPORT"]

territorio  paese  anno  mese  cumulato
309048      75     2000  9     C            53.714.988
                   2001  9     C           100.558.311
                   2002  9     C           108.431.524
                   2003  9     C            82.237.656
                   2004  9     C           103.713.482
                   2005  9     C           305.372.412
                   2006  9     C                   NaN
                   2007  9     C           259.693.665
                   2008  9     C           235.949.204
                   2009  9     C           178.188.726
                   2010  9     C           159.871.451
                   2011  9     C           234.999.174
                   2012  9     C           241.138.686
                   2013  9     C           299.414.649
Name: DATI EXPORT, dtype: object

In [55]:
Firenze_russia = coeweb("http://www.coeweb.istat.it/predefinite/tutto_paese_merce.asp?livello=ATE07_AT2&riga=MERCE&territorio=S&AG=S")

In [56]:
Firenze_russia.scarica_molti(lista_paesi = ['75'], lista_anni = lista_anni, lista_mesi = ["1","2","3","4"], lista_cumulato = ['M'])

download_309048_75_2000_1_M
download_309048_75_2000_2_M
download_309048_75_2000_3_M
download_309048_75_2000_4_M
download_309048_75_2001_1_M
download_309048_75_2001_2_M
download_309048_75_2001_3_M
download_309048_75_2001_4_M
download_309048_75_2002_1_M
download_309048_75_2002_2_M
download_309048_75_2002_3_M
download_309048_75_2002_4_M
download_309048_75_2003_1_M
download_309048_75_2003_2_M
download_309048_75_2003_3_M
download_309048_75_2003_4_M
download_309048_75_2004_1_M
download_309048_75_2004_2_M
download_309048_75_2004_3_M
download_309048_75_2004_4_M
download_309048_75_2005_1_M
download_309048_75_2005_2_M
download_309048_75_2005_3_M
download_309048_75_2005_4_M
download_309048_75_2006_1_M
download_309048_75_2006_2_M
download_309048_75_2006_3_M
download_309048_75_2006_4_M
download_309048_75_2007_1_M
download_309048_75_2007_2_M
download_309048_75_2007_3_M
download_309048_75_2007_4_M
download_309048_75_2008_1_M
download_309048_75_2008_2_M
download_309048_75_2008_3_M
download_309048_75_2008_4_M
download_309048_75_2009_1_M
download_309048_75_2009_2_M
download_309048_75_2009_3_M
download_309048_75_2009_4_M
download_309048_75_2010_1_M
download_309048_75_2010_2_M
download_309048_75_2010_3_M
download_309048_75_2010_4_M
download_309048_75_2011_1_M
download_309048_75_2011_2_M
download_309048_75_2011_3_M
download_309048_75_2011_4_M
download_309048_75_2012_1_M
download_309048_75_2012_2_M
download_309048_75_2012_3_M
download_309048_75_2012_4_M
download_309048_75_2013_1_M
download_309048_75_2013_2_M
download_309048_75_2013_3_M
download_309048_75_2013_4_M
eseguito

In [57]:
Firenze_russia.pandas_db.xs("Totale", level=0)

                                     DATI EXPORT
territorio paese anno mese cumulato
309048     75    2000 1    M          13.239.404
                      2    M          14.146.584
                      3    M          12.170.365
                      4    M          14.158.634
                 2001 1    M          12.085.556
                      2    M          17.768.444
                      3    M          17.541.660
                      4    M          53.162.651
                 2002 1    M          34.233.671
                      2    M          20.846.740
                      3    M          28.913.578
                      4    M          24.437.535
                 2003 1    M          17.565.604
                      2    M          16.285.126
                      3    M          21.136.771
                      4    M          27.250.155
                 2004 1    M          17.584.794
                      2    M          23.198.729
                      3    M          32.500.981
                      4    M          30.428.978
                 2005 1    M          45.869.480
                      2    M         108.329.489
                      3    M          90.091.169
                      4    M          61.082.274
                 2006 1    M          33.654.681
                      2    M          40.479.727
                      3    M          56.637.895
                      4    M          58.792.039
                 2007 1    M          47.271.757
                      2    M          45.375.475
                      3    M          96.276.024
                      4    M          70.770.409
                 2008 1    M          57.954.569
                      2    M          53.568.721
                      3    M          66.689.589
                      4    M          57.736.325
                 2009 1    M          38.885.134
                      2    M          59.668.296
                      3    M          43.450.336
                      4    M          36.184.960
                 2010 1    M          40.326.699
                      2    M          37.542.595
                      3    M          37.000.333
                      4    M          45.001.824
                 2011 1    M          51.633.825
                      2    M          43.052.194
                      3    M          68.336.192
                      4    M          71.976.963
                 2012 1    M          56.713.229
                      2    M          48.398.145
                      3    M          62.030.866
                      4    M          73.996.446
                 2013 1    M          86.718.677
                      2    M          54.905.672
                      3    M          98.179.667
                      4    M          59.610.633

In [ ]:

russia_pelle
russia_abbigliamento
russia_tessile
russia_moda

In [94]:
import matplotlib.pyplot as plt

In [95]:
x = lista_anni

In [96]:
x

['2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013']

In [99]:
plt.plot(x,russia_pelle["DATI EXPORT"])
plt.plot(x,russia_abbigliamento["DATI EXPORT"])
plt.plot(x,russia_tessile["DATI EXPORT"])
plt.plot(x,russia_moda["DATI EXPORT"])

In [100]:
plt.show()

In [23]:
Prato = coeweb("http://www.coeweb.istat.it/predefinite/tutto_paese_merce.asp?livello=ATE07_AT2&riga=MERCE&territorio=S&AG=S")

In [24]:
Prato.territori

[('1', "['Italia Nord-occidentale']"),
 ('101', "['---Piemonte']"),
 ('101001', "['------Torino']"),
 ('101002', "['------Vercelli']"),
 ('101003', "['------Novara']"),
 ('101004', "['------Cuneo']"),
 ('101005', "['------Asti']"),
 ('101006', "['------Alessandria']"),
 ('101096', "['------Biella']"),
 ('101103', "['------Verbano-Cusio-Ossola']"),
 ('102', '["---Valle d\'Aosta/Vall\\xe9e d\'Aoste"]'),
 ('102007', "['------Aosta']"),
 ('103', "['---Lombardia']"),
 ('103012', "['------Varese']"),
 ('103013', "['------Como']"),
 ('103014', "['------Sondrio']"),
 ('103015', "['------Milano']"),
 ('103016', "['------Bergamo']"),
 ('103017', "['------Brescia']"),
 ('103018', "['------Pavia']"),
 ('103019', "['------Cremona']"),
 ('103020', "['------Mantova']"),
 ('103097', "['------Lecco']"),
 ('103098', "['------Lodi']"),
 ('103108', "['------Monza e della Brianza']"),
 ('107', "['---Liguria']"),
 ('107008', "['------Imperia']"),
 ('107009', "['------Savona']"),
 ('107010', "['------Genova']"),
 ('107011', "['------La Spezia']"),
 ('2', "['Italia Nord-orientale']"),
 ('204', "['---Trentino-Alto Adige/S\\xfcdtirol']"),
 ('204021', "['------Bolzano/Bozen']"),
 ('204022', "['------Trento']"),
 ('205', "['---Veneto']"),
 ('205023', "['------Verona']"),
 ('205024', "['------Vicenza']"),
 ('205025', "['------Belluno']"),
 ('205026', "['------Treviso']"),
 ('205027', "['------Venezia']"),
 ('205028', "['------Padova']"),
 ('205029', "['------Rovigo']"),
 ('206', "['---Friuli-Venezia Giulia']"),
 ('206030', "['------Udine']"),
 ('206031', "['------Gorizia']"),
 ('206032', "['------Trieste']"),
 ('206093', "['------Pordenone']"),
 ('208', "['---Emilia-Romagna']"),
 ('208033', "['------Piacenza']"),
 ('208034', "['------Parma']"),
 ('208035', '["------Reggio nell\'Emilia"]'),
 ('208036', "['------Modena']"),
 ('208037', "['------Bologna']"),
 ('208038', "['------Ferrara']"),
 ('208039', "['------Ravenna']"),
 ('208040', "['------Forl\\xec-Cesena']"),
 ('208099', "['------Rimini']"),
 ('3', "['Italia Centrale']"),
 ('309', "['---Toscana']"),
 ('309045', "['------Massa-Carrara']"),
 ('309046', "['------Lucca']"),
 ('309047', "['------Pistoia']"),
 ('309048', "['------Firenze']"),
 ('309049', "['------Livorno']"),
 ('309050', "['------Pisa']"),
 ('309051', "['------Arezzo']"),
 ('309052', "['------Siena']"),
 ('309053', "['------Grosseto']"),
 ('309100', "['------Prato']"),
 ('310', "['---Umbria']"),
 ('310054', "['------Perugia']"),
 ('310055', "['------Terni']"),
 ('311', "['---Marche']"),
 ('311041', "['------Pesaro e Urbino']"),
 ('311042', "['------Ancona']"),
 ('311043', "['------Macerata']"),
 ('311044', "['------Ascoli Piceno']"),
 ('311109', "['------Fermo']"),
 ('312', "['---Lazio']"),
 ('312056', "['------Viterbo']"),
 ('312057', "['------Rieti']"),
 ('312058', "['------Roma']"),
 ('312059', "['------Latina']"),
 ('312060', "['------Frosinone']"),
 ('4', "['Italia Meridionale']"),
 ('413', "['---Abruzzo']"),
 ('413066', '["------L\'Aquila"]'),
 ('413067', "['------Teramo']"),
 ('413068', "['------Pescara']"),
 ('413069', "['------Chieti']"),
 ('414', "['---Molise']"),
 ('414070', "['------Campobasso']"),
 ('414094', "['------Isernia']"),
 ('415', "['---Campania']"),
 ('415061', "['------Caserta']"),
 ('415062', "['------Benevento']"),
 ('415063', "['------Napoli']"),
 ('415064', "['------Avellino']"),
 ('415065', "['------Salerno']"),
 ('416', "['---Puglia']"),
 ('416071', "['------Foggia']"),
 ('416072', "['------Bari']"),
 ('416073', "['------Taranto']"),
 ('416074', "['------Brindisi']"),
 ('416075', "['------Lecce']"),
 ('416110', "['------Barletta-Andria-Trani']"),
 ('417', "['---Basilicata']"),
 ('417076', "['------Potenza']"),
 ('417077', "['------Matera']"),
 ('418', "['---Calabria']"),
 ('418078', "['------Cosenza']"),
 ('418079', "['------Catanzaro']"),
 ('418080', "['------Reggio di Calabria']"),
 ('418101', "['------Crotone']"),
 ('418102', "['------Vibo Valentia']"),
 ('5', "['Italia Insulare']"),
 ('519', "['---Sicilia']"),
 ('519081', "['------Trapani']"),
 ('519082', "['------Palermo']"),
 ('519083', "['------Messina']"),
 ('519084', "['------Agrigento']"),
 ('519085', "['------Caltanissetta']"),
 ('519086', "['------Enna']"),
 ('519087', "['------Catania']"),
 ('519088', "['------Ragusa']"),
 ('519089', "['------Siracusa']"),
 ('520', "['---Sardegna']"),
 ('520090', "['------Sassari']"),
 ('520091', "['------Nuoro']"),
 ('520092', "['------Cagliari']"),
 ('520095', "['------Oristano']"),
 ('520104', "['------Olbia-Tempio']"),
 ('520105', "['------Ogliastra']"),
 ('520106', "['------Medio Campidano']"),
 ('520107', "['------Carbonia-Iglesias']"),
 ('6', "['Diverse o non specificate']"),
 ('697', "['---Regioni diverse o non specificate']"),
 ('697198', "['------Province diverse']"),
 ('697199', "['------Province non specificate e altri stati membri']"),
 ('697199', "['------Province non specificate']")]

In [21]:
#Prato.paesi_descizione

[('1', "['1 - Francia']"),
 ('2', "['2 - Belgio e Lussemburgo']"),
 ('3', "['3 - Paesi Bassi']"),
 ('4', "['4 - Germania']"),
 ('6', "['6 - Regno Unito']"),
 ('7', "['7 - Irlanda']"),
 ('8', "['8 - Danimarca']"),
 ('9', "['9 - Grecia']"),
 ('10', "['10 - Portogallo']"),
 ('11', "['11 - Spagna']"),
 ('17', "['17 - Belgio']"),
 ('18', "['18 - Lussemburgo']"),
 ('21', "['21 - Ceuta']"),
 ('22', "['22 - Ceuta e Melilla']"),
 ('23', "['23 - Melilla']"),
 ('24', "['24 - Islanda']"),
 ('25', "['25 - Isole F\\xe6r\\xf8er']"),
 ('27', "['27 - Svalbard (arcipelago delle)']"),
 ('28', "['28 - Norvegia']"),
 ('30', "['30 - Svezia']"),
 ('32', "['32 - Finlandia']"),
 ('37', "['37 - Liechtenstein']"),
 ('38', "['38 - Austria']"),
 ('39', "['39 - Svizzera']"),
 ('41', "['41 - Faer \\xd8er']"),
 ('43', "['43 - Andorra']"),
 ('44', "['44 - Gibilterra']"),
 ('45', "['45 - Santa Sede (Stato della Citt\\xe0 del Vaticano)']"),
 ('46', "['46 - Malta']"),
 ('47', "['47 - San Marino']"),
 ('48', "['48 - Iugoslavia']"),
 ('52', "['52 - Turchia']"),
 ('53', "['53 - Estonia']"),
 ('54', "['54 - Lettonia']"),
 ('55', "['55 - Lituania']"),
 ('56', "['56 - Unione Sovietica']"),
 ('60', "['60 - Polonia']"),
 ('61', "['61 - Repubblica ceca']"),
 ('62', "['62 - Cecoslovacchia']"),
 ('63', "['63 - Slovacchia']"),
 ('64', "['64 - Ungheria']"),
 ('66', "['66 - Romania']"),
 ('68', "['68 - Bulgaria']"),
 ('70', "['70 - Albania']"),
 ('72', "['72 - Ucraina']"),
 ('73', "['73 - Bielorussia']"),
 ('74', "['74 - Repubblica moldova']"),
 ('75', "['75 - Russia']"),
 ('76', "['76 - Georgia']"),
 ('77', "['77 - Armenia']"),
 ('78', "['78 - Azerbaigian']"),
 ('79', "['79 - Kazakhstan']"),
 ('80', "['80 - Turkmenistan']"),
 ('81', "['81 - Uzbekistan']"),
 ('82', "['82 - Tagikistan']"),
 ('83', "['83 - Kirghizistan']"),
 ('90', "['90 - Iugoslavia']"),
 ('91', "['91 - Slovenia']"),
 ('92', "['92 - Croazia']"),
 ('93', "['93 - Bosnia-Erzegovina']"),
 ('94', "['94 - Serbia e Montenegro']"),
 ('95', "['95 - Kosovo']"),
 ('96', "['96 - ex Repubblica iugoslava di Macedonia']"),
 ('97', "['97 - Montenegro']"),
 ('98', "['98 - Serbia']"),
 ('204', "['204 - Marocco']"),
 ('208', "['208 - Algeria']"),
 ('212', "['212 - Tunisia']"),
 ('216', "['216 - Libia']"),
 ('220', "['220 - Egitto']"),
 ('224', "['224 - Sudan']"),
 ('225', "['225 - Sud Sudan']"),
 ('228', "['228 - Mauritania']"),
 ('229', "['229 - Sahara occidentale']"),
 ('232', "['232 - Mali']"),
 ('236', "['236 - Burkina Faso']"),
 ('240', "['240 - Niger']"),
 ('244', "['244 - Ciad']"),
 ('247', "['247 - Capo Verde']"),
 ('248', "['248 - Senegal']"),
 ('252', "['252 - Gambia']"),
 ('257', "['257 - Guinea-Bissau']"),
 ('260', "['260 - Guinea']"),
 ('264', "['264 - Sierra Leone']"),
 ('268', "['268 - Liberia']"),
 ('272', '["272 - Costa d\'Avorio"]'),
 ('276', "['276 - Ghana']"),
 ('280', "['280 - Togo']"),
 ('284', "['284 - Benin']"),
 ('288', "['288 - Nigeria']"),
 ('302', "['302 - Camerun']"),
 ('306', "['306 - Repubblica centrafricana']"),
 ('310', "['310 - Guinea equatoriale']"),
 ('311', "['311 - S\\xe3o Tom\\xe9 e Principe']"),
 ('314', "['314 - Gabon']"),
 ('318', "['318 - Congo']"),
 ('322', "['322 - Repubblica democratica del Congo']"),
 ('324', "['324 - Ruanda']"),
 ('328', "['328 - Burundi']"),
 ('329', '["329 - Sant\'Elena, Ascensione e Tristan da Cunha"]'),
 ('330', "['330 - Angola']"),
 ('334', "['334 - Etiopia']"),
 ('336', "['336 - Eritrea']"),
 ('338', "['338 - Gibuti']"),
 ('342', "['342 - Somalia']"),
 ('346', "['346 - Kenya']"),
 ('350', "['350 - Uganda']"),
 ('352', "['352 - Repubblica unita di Tanzania']"),
 ('355', "['355 - Seychelles']"),
 ('357', '["357 - Territorio britannico dell\'Oceano Indiano"]'),
 ('366', "['366 - Mozambico']"),
 ('370', "['370 - Madagascar']"),
 ('372', "['372 - Riunione']"),
 ('373', "['373 - Maurizio']"),
 ('375', "['375 - Comore']"),
 ('377', "['377 - Mayotte']"),
 ('378', "['378 - Zambia']"),
 ('382', "['382 - Zimbabwe']"),
 ('386', "['386 - Malawi']"),
 ('388', "['388 - Sud Africa']"),
 ('389', "['389 - Namibia']"),
 ('391', "['391 - Botswana']"),
 ('393', "['393 - Swaziland']"),
 ('395', "['395 - Lesotho']"),
 ('400', "['400 - Stati Uniti']"),
 ('404', "['404 - Canada']"),
 ('406', "['406 - Groenlandia']"),
 ('408', "['408 - Saint Pierre e Miquelon']"),
 ('412', "['412 - Messico']"),
 ('413', "['413 - Bermuda']"),
 ('416', "['416 - Guatemala']"),
 ('421', "['421 - Belize']"),
 ('424', "['424 - Honduras']"),
 ('428', "['428 - El Salvador']"),
 ('432', "['432 - Nicaragua']"),
 ('436', "['436 - Costa Rica']"),
 ('442', "['442 - Panama']"),
 ('446', "['446 - Anguilla']"),
 ('448', "['448 - Cuba']"),
 ('449', "['449 - Saint Kitts e Nevis']"),
 ('452', "['452 - Haiti']"),
 ('453', "['453 - Bahamas']"),
 ('454', "['454 - Isole Turks e Caicos']"),
 ('456', "['456 - Repubblica dominicana']"),
 ('457', "['457 - Isole Vergini americane']"),
 ('458', "['458 - Guadalupa']"),
 ('459', "['459 - Antigua e Barbuda']"),
 ('460', "['460 - Dominica']"),
 ('461', "['461 - Isole Vergini britanniche']"),
 ('462', "['462 - Martinica']"),
 ('463', "['463 - Isole Cayman']"),
 ('464', "['464 - Giamaica']"),
 ('465', "['465 - Santa Lucia']"),
 ('466', "['466 - Saint-Barth\\xe9lemy']"),
 ('467', "['467 - Saint Vincent e Grenadine']"),
 ('468', "['468 - Isole Vergini britanniche']"),
 ('469', "['469 - Barbados']"),
 ('470', "['470 - Montserrat']"),
 ('472', "['472 - Trinidad e Tobago']"),
 ('473', "['473 - Grenada']"),
 ('474', "['474 - Aruba']"),
 ('475', "['475 - Cura\\xe7ao']"),
 ('477', "['477 - Bonaire, Sint Eustatius e Saba']"),
 ('478', "['478 - Antille Olandesi']"),
 ('479', "['479 - Sint Maarten']"),
 ('480', "['480 - Colombia']"),
 ('484', "['484 - Venezuela']"),
 ('488', "['488 - Guyana']"),
 ('492', "['492 - Suriname']"),
 ('496', "['496 - Guiana Francese']"),
 ('500', "['500 - Ecuador']"),
 ('504', "['504 - Per\\xf9']"),
 ('508', "['508 - Brasile']"),
 ('512', "['512 - Cile']"),
 ('516', "['516 - Bolivia']"),
 ('520', "['520 - Paraguay']"),
 ('524', "['524 - Uruguay']"),
 ('528', "['528 - Argentina']"),
 ('529', "['529 - Isole Falkland']"),
 ('600', "['600 - Cipro']"),
 ('604', "['604 - Libano']"),
 ('608', "['608 - Siria']"),
 ('612', "['612 - Iraq']"),
 ('616', '["616 - Repubblica islamica dell\'Iran"]'),
 ('624', "['624 - Israele']"),
 ('625', "['625 - Territorio palestinese occupato']"),
 ('626', "['626 - Timor-Leste']"),
 ('628', "['628 - Giordania']"),
 ('632', "['632 - Arabia Saudita']"),
 ('636', "['636 - Kuwait']"),
 ('640', "['640 - Bahrein']"),
 ('644', "['644 - Qatar']"),
 ('647', "['647 - Emirati Arabi Uniti']"),
 ('649', "['649 - Oman']"),
 ('653', "['653 - Yemen']"),
 ('660', "['660 - Afghanistan']"),
 ('662', "['662 - Pakistan']"),
 ('664', "['664 - India']"),
 ('666', "['666 - Bangladesh']"),
 ('667', "['667 - Maldive']"),
 ('669', "['669 - Sri Lanka']"),
 ('672', "['672 - Nepal']"),
 ('675', "['675 - Bhutan']"),
 ('676', "['676 - Birmania']"),
 ('680', "['680 - Thailandia']"),
 ('684', "['684 - Laos']"),
 ('690', "['690 - Vietnam']"),
 ('696', "['696 - Cambogia']"),
 ('700', "['700 - Indonesia']"),
 ('701', "['701 - Malaysia']"),
 ('703', "['703 - Brunei']"),
 ('706', "['706 - Singapore']"),
 ('708', "['708 - Filippine']"),
 ('716', "['716 - Mongolia']"),
 ('720', "['720 - Cina']"),
 ('724', "['724 - Corea del Nord']"),
 ('728', "['728 - Corea del Sud']"),
 ('732', "['732 - Giappone']"),
 ('736', "['736 - Taiwan']"),
 ('740', "['740 - Hong Kong']"),
 ('743', "['743 - Macao']"),
 ('800', "['800 - Australia']"),
 ('801', "['801 - Papua Nuova Guinea']"),
 ('802', "['802 - Oceania australiana']"),
 ('803', "['803 - Nauru']"),
 ('804', "['804 - Nuova Zelanda']"),
 ('806', "['806 - Isole Salomone']"),
 ('807', "['807 - Tuvalu']"),
 ('808', "['808 - Oceania americana']"),
 ('809', "['809 - Nuova Caledonia']"),
 ('810', "['810 - Oceania americana']"),
 ('811', "['811 - Wallis e Futuna']"),
 ('812', "['812 - Kiribati']"),
 ('813', "['813 - Isole Pitcairn']"),
 ('814', "['814 - Oceania neozelandese']"),
 ('815', "['815 - Figi']"),
 ('816', "['816 - Vanuatu']"),
 ('817', "['817 - Tonga']"),
 ('819', "['819 - Samoa']"),
 ('820', "['820 - Isole Marianne settentrionali']"),
 ('822', "['822 - Polinesia francese']"),
 ('823', "['823 - Stati Federati di Micronesia']"),
 ('824', "['824 - Isole Marshall']"),
 ('825', "['825 - Palau']"),
 ('830', "['830 - Samoa americane']"),
 ('831', "['831 - Guam']"),
 ('832', "['832 - Isole minori periferiche degli Stati Uniti']"),
 ('833', "['833 - Isole Cocos (Keeling)']"),
 ('834', "['834 - Isola Christmas']"),
 ('835', "['835 - Isole Heard e McDonald']"),
 ('836', "['836 - Isola Norfolk']"),
 ('837', "['837 - Isole Cook']"),
 ('838', "['838 - Niue']"),
 ('839', "['839 - Tokelau']"),
 ('890', "['890 - Regioni Polari']"),
 ('891', "['891 - Antartide']"),
 ('892', "['892 - Isola di Bouvet']"),
 ('893', "['893 - Georgia del Sud e Sandwich australi']"),
 ('894', "['894 - Terre australi e antartiche francesi']"),
 ('950', "['950 - Provviste e dotazioni di bordo']"),
 ('951',
  "['951 - Provviste e dotazioni di bordo nel quadro degli scambi intra UE']"),
 ('952',
  "['952 - Provviste e dotazioni di bordo nel quadro degli scambi con paesi terzi']"),
 ('955', "['955 - Alto mare']"),
 ('958', "['958 - Paesi e territori non specificati']"),
 ('959',
  "['959 - Paesi e territori non specificati nel quadro degli scambi intra UE']"),
 ('960',
  "['960 - Paesi e territori non specificati nel quadro degli scambi con i paesi terzi']"),
 ('962', "['962 - Punti e depositi franchi']"),
 ('977',
  "['977 - Paesi e territori non specificati per ragioni commerciali o militari']"),
 ('978',
  "['978 - Paesi e territori non specificati per ragioni commerciali o militari (intra UE)']"),
 ('979',
  "['979 - Paesi e territori non specificati per ragioni commerciali o militari (extra UE)']"),
 ('1001', "['1001 - [Uem12]']"),
 ('1002', "['1002 - [Unione europea 15]']"),
 ('1004', "['1004 - [EFTA]']"),
 ('1005', "['1005 - [CEFTA]']"),
 ('1006', "['1006 - [COMESA]']"),
 ('1007', "['1007 - [SACU]']"),
 ('1008', "['1008 - [ASEAN]']"),
 ('1009', "['1009 - [NAFTA]']"),
 ('1010', '["1010 - [COMUNITA\' ANDINA]"]'),
 ('1011', "['1011 - [MERCOSUR]']"),
 ('1012', "['1012 - [OPEC]']"),
 ('1013', "['1013 - [EUROPA]']"),
 ('1015', "['1015 - [Paesi europei non Ue]']"),
 ('1016', "['1016 - [AFRICA]']"),
 ('1017', "['1017 - [Africa settentrionale]']"),
 ('1018', "['1018 - [Altri paesi africani]']"),
 ('1019', "['1019 - [AMERICA]']"),
 ('1020', "['1020 - [America settentrionale]']"),
 ('1021', "['1021 - [America centro-meridionale]']"),
 ('1022', "['1022 - [ASIA]']"),
 ('1023', "['1023 - [Medio Oriente]']"),
 ('1024', "['1024 - [Asia centrale]']"),
 ('1025', "['1025 - [Asia orientale]']"),
 ('1026', "['1026 - [Oceania]']"),
 ('1027', "['1027 - [Altri territori]']"),
 ('1028', "['1028 - [AREA DEL MEDITERRANEO]']"),
 ('1032', "['1032 - [Altre destinazioni]']"),
 ('1033', "['1033 - [MONDO]']"),
 ('1034', "['1034 - [OCEANIA E ALTRI TERRITORI]']"),
 ('1035', "['1035 - [NIEs]']"),
 ('1036', "['1036 - [Unione europea 25]']"),
 ('1038', "['1038 - [Unione europea 27]']"),
 ('1042', "['1042 - [EDA]']"),
 ('1044', "['1044 - [Uem17]']"),
 ('1045', "['1045 - [Unione europea 28]']"),
 ('1046', "['1046 - [Extra Ue 28]']"),
 ('1047', "['1047 - [Uem18]']"),
 ('1048', "['1048 - [BRICS]']"),
 ('1049', "['1049 - [APEC]']")]

In [26]:
Prato.scarica_molti(territorio = ['309100'], lista_paesi = ['75'], lista_anni = lista_anni, lista_mesi = ["9"], lista_cumulato = ['C'])

download_309100_75_2000_9_C
download_309100_75_2001_9_C
download_309100_75_2002_9_C
download_309100_75_2003_9_C
download_309100_75_2004_9_C
download_309100_75_2005_9_C
download_309100_75_2006_9_C
download_309100_75_2007_9_C
download_309100_75_2008_9_C
download_309100_75_2009_9_C
download_309100_75_2010_9_C
download_309100_75_2011_9_C
download_309100_75_2012_9_C
download_309100_75_2013_9_C
eseguito

In [27]:
Prato.pandas_db.xs("Totale", level=0)

                                    DATI EXPORT
territorio paese anno mese cumulato
309100     75    2000 9    C         41.164.567
                 2001 9    C         69.102.171
                 2002 9    C         65.398.909
                 2003 9    C         67.978.942
                 2004 9    C         63.422.877
                 2005 9    C         61.965.012
                 2006 9    C         81.485.512
                 2007 9    C         79.678.885
                 2008 9    C         81.923.831
                 2009 9    C         49.462.404
                 2010 9    C         61.070.919
                 2011 9    C         62.638.447
                 2012 9    C         62.142.354
                 2013 9    C         57.907.409

In [33]:
prato_russia_pelle =Prato.pandas_db.xs("CB15-Articoli in pelle (escluso abbigliamento) e simili", level=0)

In [37]:
prato_russia_pelle["DATI EXPORT"] = prato_russia_pelle["DATI EXPORT"].apply(lambda x: convert_string_euro(x)).interpolate()

-c:1: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_index,col_indexer] = value instead

In [38]:
prato_russia_pelle

                                     DATI EXPORT
territorio paese anno mese cumulato
309100     75    2000 9    C              158632
                 2001 9    C              231660
                 2002 9    C              154799
                 2003 9    C              165903
                 2004 9    C              408330
                 2005 9    C              247950
                 2006 9    C              485980
                 2007 9    C              989799
                 2008 9    C             1533530
                 2009 9    C              583504
                 2010 9    C              508496
                 2011 9    C              335156
                 2012 9    C              236883
                 2013 9    C              281692

In [42]:
prato_russia_abbigliamento =Prato.pandas_db.xs("CB14-Articoli di abbigliamento (anche in pelle e in pelliccia)", level=0)
prato_russia_abbigliamento["DATI EXPORT"] = prato_russia_abbigliamento["DATI EXPORT"].apply(lambda x: convert_string_euro(x)).interpolate()
prato_russia_abbigliamento

-c:2: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_index,col_indexer] = value instead

                                     DATI EXPORT
territorio paese anno mese cumulato
309100     75    2000 9    C             1751976
                 2001 9    C             2834047
                 2002 9    C             2637805
                 2003 9    C             4272491
                 2004 9    C             7127862
                 2005 9    C             9249844
                 2006 9    C            14067698
                 2007 9    C            14605224
                 2008 9    C            16611356
                 2009 9    C             9289334
                 2010 9    C             6243681
                 2011 9    C             7201130
                 2012 9    C             7653014
                 2013 9    C             6779333

In [43]:
prato_russia_tessile =Prato.pandas_db.xs("CB13-Prodotti tessili", level=0)
prato_russia_tessile["DATI EXPORT"] = prato_russia_tessile["DATI EXPORT"].apply(lambda x: convert_string_euro(x)).interpolate()
prato_russia_tessile

                                     DATI EXPORT
territorio paese anno mese cumulato
309100     75    2000 9    C            34583096
                 2001 9    C            59201427
                 2002 9    C            58877882
                 2003 9    C            57038863
                 2004 9    C            46241932
                 2005 9    C            46519498
                 2006 9    C            56888459
                 2007 9    C            49360000
                 2008 9    C            51626071
                 2009 9    C            34345469
                 2010 9    C            45965930
                 2011 9    C            44855837
                 2012 9    C            47925262
                 2013 9    C            42187800

In [45]:
prato_russia_moda = prato_russia_tessile + prato_russia_abbigliamento + prato_russia_pelle

In [46]:
prato_russia_moda

                                     DATI EXPORT
territorio paese anno mese cumulato
309100     75    2000 9    C            36493704
                 2001 9    C            62267134
                 2002 9    C            61670486
                 2003 9    C            61477257
                 2004 9    C            53778124
                 2005 9    C            56017292
                 2006 9    C            71442137
                 2007 9    C            64955023
                 2008 9    C            69770957
                 2009 9    C            44218307
                 2010 9    C            52718107
                 2011 9    C            52392123
                 2012 9    C            55815159
                 2013 9    C            49248825

In [47]:
prato_russia_agricoli =Prato.pandas_db.xs("AA01-Prodotti agricoli, animali e della caccia", level=0)
prato_russia_agricoli["DATI EXPORT"] = prato_russia_agricoli["DATI EXPORT"].apply(lambda x: convert_string_euro(x)).interpolate()
prato_russia_agricoli

                                     DATI EXPORT
territorio paese anno mese cumulato
309100     75    2000 9    C                   0
                 2001 9    C                   0
                 2002 9    C                   0
                 2003 9    C                3527
                 2004 9    C                 597
                 2005 9    C                5736
                 2006 9    C                   0
                 2007 9    C                1524
                 2008 9    C                   0
                 2009 9    C                   0
                 2010 9    C              415251
                 2011 9    C              301473
                 2012 9    C               58826
                 2013 9    C               20150

In [ ]:
prato_russia_tessile + prato_russia_abbigliamento + prato_russia_pelle + 
prato_russia_agricoli + prato_russia_moda

In [48]:
prato_russia_Totale =Prato.pandas_db.xs("Totale", level=0)
prato_russia_Totale["DATI EXPORT"] = prato_russia_Totale["DATI EXPORT"].apply(lambda x: convert_string_euro(x)).interpolate()
prato_russia_Totale

                                     DATI EXPORT
territorio paese anno mese cumulato
309100     75    2000 9    C            41164567
                 2001 9    C            69102171
                 2002 9    C            65398909
                 2003 9    C            67978942
                 2004 9    C            63422877
                 2005 9    C            61965012
                 2006 9    C            81485512
                 2007 9    C            79678885
                 2008 9    C            81923831
                 2009 9    C            49462404
                 2010 9    C            61070919
                 2011 9    C            62638447
                 2012 9    C            62142354
                 2013 9    C            57907409

In [49]:
writer = pd.ExcelWriter('Prato.xlsx')
prato_russia_pelle.to_excel(writer,'pelle')
prato_russia_abbigliamento.to_excel(writer,'abbigliamento')
prato_russia_tessile.to_excel(writer,'tessile')
prato_russia_agricoli.to_excel(writer,'agricoli')
prato_russia_moda.to_excel(writer,'moda')
prato_russia_Totale.to_excel(writer,'Totale')
writer.save()

In [5]:
province = coeweb("http://www.coeweb.istat.it/predefinite/tutto_paese_merce.asp?livello=ATE07_AT2&riga=MERCE&territorio=S&AG=S")

In [29]:
toscanalist = []
toscanaspieg = []
for item in province.territori:
    if item[0][:3] =="309":
        toscanalist.append(item[0])
        toscanaspieg.append(item)

In [32]:
pd.DataFrame(toscanaspieg).to_excel("legenda.xlsx")

In [8]:
province.scarica_molti(territorio = [
 '309045',
 '309046',
 '309047',
 '309048',
 '309049'], lista_paesi = ["1033"], lista_anni = ["2009","2013"], lista_mesi = ["9"], lista_cumulato = ['C'])

download_309045_1033_2009_9_C
download_309045_1033_2013_9_C
download_309046_1033_2009_9_C
download_309046_1033_2013_9_C
download_309047_1033_2009_9_C
download_309047_1033_2013_9_C
download_309048_1033_2009_9_C
download_309048_1033_2013_9_C
download_309049_1033_2009_9_C
download_309049_1033_2013_9_C
eseguito

In [12]:
prima_trance = province.pandas_db

In [13]:
province.scarica_molti(territorio = [
 '309050',
 '309051',
 '309052',
 '309053',
 '309100'], lista_paesi = ["1033"], lista_anni = ["2009","2013"], lista_mesi = ["9"], lista_cumulato = ['C'])

download_309050_1033_2009_9_C
download_309050_1033_2013_9_C
download_309051_1033_2009_9_C
download_309051_1033_2013_9_C
download_309052_1033_2009_9_C
download_309052_1033_2013_9_C
download_309053_1033_2009_9_C
download_309053_1033_2013_9_C
download_309100_1033_2009_9_C
download_309100_1033_2013_9_C
eseguito

In [14]:
prima_trance.shape

(380, 1)

In [16]:
seconda_trance = province.pandas_db

In [18]:
completo = pd.concat([prima_trance, seconda_trance])

In [19]:
completo.Totale("Totale"

                                                                                                                                                                         DATI EXPORT
Divisioni                                                                                                                         territorio paese anno mese cumulato
AA01-Prodotti agricoli, animali e della caccia                                                                                    309045     1033  2009 9    C             3.194.409
AA02-Prodotti della silvicoltura                                                                                                  309045     1033  2009 9    C                 4.050
AA03-Prodotti della pesca e dell'acquacoltura                                                                                     309045     1033  2009 9    C                     0
BB07-Minerali metalliferi                                                                                                         309045     1033  2009 9    C                62.273
BB08-Altri minerali da cave e miniere                                                                                             309045     1033  2009 9    C           111.182.088
CA10-Prodotti alimentari                                                                                                          309045     1033  2009 9    C               651.433
CA11-Bevande                                                                                                                      309045     1033  2009 9    C               227.180
CA12-Tabacco                                                                                                                      309045     1033  2009 9    C               390.091
CB13-Prodotti tessili                                                                                                             309045     1033  2009 9    C             2.033.377
CB14-Articoli di abbigliamento (anche in pelle e in pelliccia)                                                                    309045     1033  2009 9    C             9.919.588
CB15-Articoli in pelle (escluso abbigliamento) e simili                                                                           309045     1033  2009 9    C             1.333.497
CC16-Legno e prodotti in legno e sughero (esclusi i mobili); articoli in paglia e materiali da intreccio                          309045     1033  2009 9    C               152.163
CC17-Carta e prodotti di carta                                                                                                    309045     1033  2009 9    C             4.847.736
CD19-Coke e prodotti derivanti dalla raffinazione del petrolio                                                                    309045     1033  2009 9    C             1.572.820
CE20-Prodotti chimici                                                                                                             309045     1033  2009 9    C            26.271.994
CF21-Prodotti farmaceutici di base e preparati farmaceutici                                                                       309045     1033  2009 9    C               260.749
CG22-Articoli in gomma e materie plastiche                                                                                        309045     1033  2009 9    C             1.971.951
CG23-Altri prodotti della lavorazione di minerali non metalliferi                                                                 309045     1033  2009 9    C           244.777.262
CH24-Prodotti della metallurgia                                                                                                   309045     1033  2009 9    C             8.243.361
CH25-Prodotti in metallo, esclusi macchinari e attrezzature                                                                       309045     1033  2009 9    C            14.090.719
CI26-Computer e prodotti di elettronica e ottica; apparecchi elettromedicali, apparecchi di misurazione e orologi                 309045     1033  2009 9    C             7.309.031
CJ27-Apparecchiature elettriche e apparecchiature per uso domestico non elettriche                                                309045     1033  2009 9    C             4.496.786
CK28-Macchinari e apparecchiature nca                                                                                             309045     1033  2009 9    C           963.268.105
CL29-Autoveicoli, rimorchi e semirimorchi                                                                                         309045     1033  2009 9    C             6.615.964
CL30-Altri mezzi di trasporto                                                                                                     309045     1033  2009 9    C            13.301.093
CM31-Mobili                                                                                                                       309045     1033  2009 9    C               579.008
CM32-Prodotti delle altre industrie manifatturiere                                                                                309045     1033  2009 9    C               619.675
DD35-Energia elettrica, gas, vapore e aria condizionata                                                                           309045     1033  2009 9    C                     0
EE38-Prodotti delle attività di raccolta, trattamento e smaltimento dei rifiuti; prodotti dell'attività di recupero dei materiali 309045     1033  2009 9    C               124.220
JA58-Prodotti delle attività editoriali                                                                                           309045     1033  2009 9    C               212.659
...                                                                                                                                                                              ...
CA12-Tabacco                                                                                                                      309100     1033  2013 9    C                     0
CB13-Prodotti tessili                                                                                                             309100     1033  2013 9    C         1.167.723.370
CB14-Articoli di abbigliamento (anche in pelle e in pelliccia)                                                                    309100     1033  2013 9    C           550.985.571
CB15-Articoli in pelle (escluso abbigliamento) e simili                                                                           309100     1033  2013 9    C            28.280.205
CC16-Legno e prodotti in legno e sughero (esclusi i mobili); articoli in paglia e materiali da intreccio                          309100     1033  2013 9    C             2.619.425
CC17-Carta e prodotti di carta                                                                                                    309100     1033  2013 9    C             4.752.801
CC18-Prodotti della stampa e della riproduzione di supporti registrati                                                            309100     1033  2013 9    C                13.553
CD19-Coke e prodotti derivanti dalla raffinazione del petrolio                                                                    309100     1033  2013 9    C                16.196
CE20-Prodotti chimici                                                                                                             309100     1033  2013 9    C            56.388.012
CF21-Prodotti farmaceutici di base e preparati farmaceutici                                                                       309100     1033  2013 9    C            39.903.974
CG22-Articoli in gomma e materie plastiche                                                                                        309100     1033  2013 9    C            28.305.339
CG23-Altri prodotti della lavorazione di minerali non metalliferi                                                                 309100     1033  2013 9    C             6.230.081
CH24-Prodotti della metallurgia                                                                                                   309100     1033  2013 9    C             5.000.451
CH25-Prodotti in metallo, esclusi macchinari e attrezzature                                                                       309100     1033  2013 9    C             7.629.723
CI26-Computer e prodotti di elettronica e ottica; apparecchi elettromedicali, apparecchi di misurazione e orologi                 309100     1033  2013 9    C             9.088.324
CJ27-Apparecchiature elettriche e apparecchiature per uso domestico non elettriche                                                309100     1033  2013 9    C             8.305.979
CK28-Macchinari e apparecchiature nca                                                                                             309100     1033  2013 9    C           100.288.031
CL29-Autoveicoli, rimorchi e semirimorchi                                                                                         309100     1033  2013 9    C             4.271.093
CL30-Altri mezzi di trasporto                                                                                                     309100     1033  2013 9    C            11.175.376
CM31-Mobili                                                                                                                       309100     1033  2013 9    C            61.437.154
CM32-Prodotti delle altre industrie manifatturiere                                                                                309100     1033  2013 9    C             5.291.188
EE38-Prodotti delle attività di raccolta, trattamento e smaltimento dei rifiuti; prodotti dell'attività di recupero dei materiali 309100     1033  2013 9    C             4.721.150
JA58-Prodotti delle attività editoriali                                                                                           309100     1033  2013 9    C               615.154
JA59-Prodotti delle attività di produzione cinematografica, video e programmi televisivi; registrazioni musicali e sonore         309100     1033  2013 9    C                35.410
RR90-Prodotti delle attività creative, artistiche e d'intrattenimento                                                             309100     1033  2013 9    C             1.754.846
RR91-Prodotti delle attività di biblioteche, archivi, musei e di altre attività culturali                                         309100     1033  2013 9    C                14.080
SS96-Prodotti delle altre attività di servizi per la persona                                                                      309100     1033  2013 9    C                     0
VV89-Merci dichiarate come provviste di bordo, merci nazionali di ritorno e respinte, merci varie                                 309100     1033  2013 9    C               107.321
Totale                                                                                                                            309100     1033  2013 9    C         2.133.091.309
NaN                                                                                                                               309100     1033  2013 9    C                   NaN

[755 rows x 1 columns]

In [20]:
completo

AttributeError: 'DataFrame' object has no attribute 'analizza_settori'

In [21]:
  def convert_string_euro(x):
        '''questa funzione rimuove la formattazione dei numeri di coeweb, trasformando il testo in numeri'''
        try: 
            return float(x.replace(".", ""))
        except:
            pass

In [25]:
completo = completo["DATI EXPORT"].apply(convert_string_euro)

In [28]:
pd.DataFrame(completo).to_excel("province_toscana.xlsx")